from __future__ import annotations

from pathlib import Path

from .meta import DOC_URL, ISSUES_URL, API_URL

PACKAGE_ROOT = Path(__file__).resolve().parents[2]

META = {
    "doc_url": DOC_URL,
    "issues_url": ISSUES_URL,
    "api_url": API_URL,
}

CATALOG = {
    "info": {
        "ExperimentalPath": {
            "code": "MSM-INFO-EXP-001",
            "source": "molsysmt.info.experimental",
            "category": "experimental",
            "level": "INFO",
        },
        "SupportTier3Info": {
            "code": "MSM-INFO-TIER-003",
            "source": "molsysmt.info.tier3",
            "category": "support_tier",
            "level": "INFO",
        },
        "HeavyPathSelected": {
            "code": "MSM-INFO-HVY-001",
            "source": "molsysmt.info.heavy.path_selected",
            "category": "execution",
            "level": "INFO",
        },
        "EagerPathAccepted": {
            "code": "MSM-INFO-HVY-002",
            "source": "molsysmt.info.heavy.eager_accepted",
            "category": "execution",
            "level": "INFO",
        },
        "ChunkProcessed": {
            "code": "MSM-INFO-HVY-003",
            "source": "molsysmt.info.heavy.chunk_processed",
            "category": "execution",
            "level": "INFO",
        },
    },
    "debug": {
        "DetectionProbeMiss": {
            "code": "MSM-DBG-PROBE-001",
            "source": "molsysmt.debug.probe",
            "category": "detection",
            "level": "DEBUG",
        },
    },
    "warnings": {
        "SupportTier2Warning": {
            "code": "MSM-WARN-TIER-002",
            "source": "molsysmt.warning.tier2",
            "category": "support_tier",
            "level": "WARNING",
        },
        "SelectionWarning": {
            "code": "MSM-WARN-SEL-001",
            "source": "molsysmt.warning.selection",
            "category": "selection",
            "level": "WARNING",
        },
        "MolSysMTDeprecationWarning": {
            "code": "MSM-WARN-DEP-001",
            "source": "molsysmt.warning.deprecation",
            "category": "deprecation",
            "level": "WARNING",
        },
        "CrossChainCovalentBondsWarning": {
            "code": "MSM-WARN-STRUCT-001",
            "source": "molsysmt.warning.cross_chain_bonds",
            "category": "structure",
            "level": "WARNING",
        },
        "DownloadWarning": {
            "code": "MSM-WARN-DL-001",
            "source": "molsysmt.warning.download",
            "category": "io",
            "level": "WARNING",
        },
        "NotDigestedArgumentWarning": {
            "code": "MSM-WARN-ARG-001",
            "source": "molsysmt.warning.not_digested",
            "category": "argument",
            "level": "WARNING",
        },
        "NumbaJitWarning": {
            "code": "MSM-WARN-NB-001",
            "source": "molsysmt.warning.numba_jit",
            "category": "performance",
            "level": "WARNING",
        },
        "MultiContainerWarning": {
            "code": "MSM-WARN-IO-002",
            "source": "molsysmt.warning.multi_container",
            "category": "io",
            "level": "WARNING",
        },
        "AmbiguousStructureWarning": {
            "code": "MSM-WARN-STRUCT-002",
            "source": "molsysmt.warning.ambiguous_structure",
            "category": "structure",
            "level": "WARNING",
        },
        "MolecularSystemMismatchWarning": {
            "code": "MSM-WARN-STRUCT-004",
            "source": "molsysmt.warning.molecular_system_mismatch",
            "category": "structure",
            "level": "WARNING",
        },
        "SlowChunkIOWarning": {
            "code": "MSM-WARN-HVY-001",
            "source": "molsysmt.warning.heavy.slow_io",
            "category": "performance",
            "level": "WARNING",
        },
        "CorruptFrameSkippedWarning": {
            "code": "MSM-WARN-HVY-002",
            "source": "molsysmt.warning.heavy.corrupt_frame",
            "category": "data_quality",
            "level": "WARNING",
        },
        "MemoryPressureWarning": {
            "code": "MSM-WARN-HVY-003",
            "source": "molsysmt.warning.heavy.memory_pressure",
            "category": "performance",
            "level": "WARNING",
        },
        "GpuNotAvailableWarning": {
            "code": "MSM-WARN-GPU-001",
            "source": "molsysmt.warning.gpu.not_available",
            "category": "performance",
            "level": "WARNING",
        },
    },
    "exceptions": {
        "ArgumentError": {
            "code": "MSM-ERR-ARG-001",
            "source": "molsysmt.error.argument",
            "category": "argument",
            "level": "ERROR",
        },
        "ArgumentChoiceError": {
            "code": "MSM-ERR-ARG-002",
            "source": "molsysmt.error.argument.choice",
            "category": "argument",
            "level": "ERROR",
        },
        "ArgumentLengthError": {
            "code": "MSM-ERR-ARG-003",
            "source": "molsysmt.error.argument.length",
            "category": "argument",
            "level": "ERROR",
        },
        "ArgumentConflictError": {
            "code": "MSM-ERR-ARG-004",
            "source": "molsysmt.error.argument.conflict",
            "category": "argument",
            "level": "ERROR",
        },
        "StructuralInconsistencyError": {
            "code": "MSM-ERR-STRUCT-003",
            "source": "molsysmt.error.structure.inconsistency",
            "category": "structure",
            "level": "ERROR",
        },
        "InternalAlgorithmError": {
            "code": "MSM-ERR-INT-001",
            "source": "molsysmt.error.internal.algorithm",
            "category": "internal",
            "level": "ERROR",
        },
        "IteratorError": {
            "code": "MSM-ERR-ITER-001",
            "source": "molsysmt.error.iterator",
            "category": "iterator",
            "level": "ERROR",
        },
        "LibraryNotFoundError": {
            "code": "MSM-ERR-DEP-001",
            "source": "molsysmt.error.library_not_found",
            "category": "dependency",
            "level": "ERROR",
        },
        "MolecularSystemNeededError": {
            "code": "MSM-ERR-SYS-001",
            "source": "molsysmt.error.molecular_system_needed",
            "category": "system",
            "level": "ERROR",
        },
        "MolecularSystemsNeededError": {
            "code": "MSM-ERR-SYS-002",
            "source": "molsysmt.error.molecular_systems_needed",
            "category": "system",
            "level": "ERROR",
        },
        "NotCompatibleConversionError": {
            "code": "MSM-ERR-CONV-001",
            "source": "molsysmt.error.not_compatible_conversion",
            "category": "conversion",
            "level": "ERROR",
        },
        "NotImplementedConversionError": {
            "code": "MSM-ERR-CONV-002",
            "source": "molsysmt.error.not_implemented_conversion",
            "category": "conversion",
            "level": "ERROR",
        },
        "NotImplementedIteratorError": {
            "code": "MSM-ERR-ITER-002",
            "source": "molsysmt.error.not_implemented_iterator",
            "category": "iterator",
            "level": "ERROR",
        },
        "NotImplementedMethodError": {
            "code": "MSM-ERR-METHOD-001",
            "source": "molsysmt.error.not_implemented_method",
            "category": "not_implemented",
            "level": "ERROR",
        },
        "NotSupportedFormError": {
            "code": "MSM-ERR-FORM-001",
            "source": "molsysmt.error.not_supported_form",
            "category": "not_supported",
            "level": "ERROR",
        },
        "NotSupportedSyntaxError": {
            "code": "MSM-ERR-SYNTAX-001",
            "source": "molsysmt.error.not_supported_syntax",
            "category": "not_supported",
            "level": "ERROR",
        },
        "NotWithThisFormError": {
            "code": "MSM-ERR-FORM-002",
            "source": "molsysmt.error.not_with_this_form",
            "category": "not_supported",
            "level": "ERROR",
        },
        "FileAlreadyHandledError": {
            "code": "MSM-ERR-IO-001",
            "source": "molsysmt.error.file_already_handled",
            "category": "io",
            "level": "ERROR",
        },
        "FileContentError": {
            "code": "MSM-ERR-IO-002",
            "source": "molsysmt.error.file_content",
            "category": "io",
            "level": "ERROR",
        },
        "FormatError": {
            "code": "MSM-ERR-IO-003",
            "source": "molsysmt.error.format",
            "category": "io",
            "level": "ERROR",
        },
        "UnsupportedHeavyOperationError": {
            "code": "MSM-ERR-HVY-001",
            "source": "molsysmt.error.heavy.unsupported_operation",
            "category": "execution",
            "level": "ERROR",
        },
        "HeavyOutputFailureError": {
            "code": "MSM-ERR-HVY-002",
            "source": "molsysmt.error.heavy.output_failure",
            "category": "io",
            "level": "ERROR",
        },
    },
}

CODES = {
    "MSM-WARN-TIER-002": {
        "title": "Best-effort supported form or function (Tier 2)",
        "user_message": "'{name}' is a best-effort supported {kind} (Tier 2). "
                        "Results are supported but not contractually guaranteed for all workflows.",
        "user_hint": "For production workflows, prefer Tier 1 forms where possible. "
                     "See the support-tier documentation at {doc_url}",
        "dev_message": "Tier 2 {kind} used: '{name}'.",
        "dev_hint": "Consider whether the calling workflow requires a Tier 1 alternative.",
        "qa_message": "Tier 2 {kind} used: '{name}'.",
        "qa_hint": "Verify that Tier 2 semantics are acceptable for this test case.",
        "agent_message": "Tier 2 {kind}: '{name}'. Not contractually guaranteed.",
        "agent_hint": "Prefer Tier 1 forms for validated workflows.",
    },
    "MSM-INFO-TIER-003": {
        "title": "Experimental or niche form/function (Tier 3)",
        "user_message": "'{name}' is an experimental or niche {kind} (Tier 3). Use with caution.",
        "user_hint": "Tier 3 items are outside the contractual 1.x support surface. "
                     "See {doc_url}",
        "dev_message": "Tier 3 {kind} used: '{name}'.",
        "dev_hint": "This item is outside the contractual support surface.",
        "qa_message": "Tier 3 {kind} used: '{name}'.",
        "qa_hint": "Tier 3 items should not appear in production or Tier 1 test paths.",
        "agent_message": "Tier 3 {kind}: '{name}'. Experimental, outside support contract.",
        "agent_hint": "Do not rely on this item for validated workflows.",
    },
    "MSM-INFO-EXP-001": {
        "title": "Experimental path",
        "user_message": "This functionality is experimental and may change.",
        "user_hint": "Use with caution. Docs: {doc_url}",
        "dev_message": "Experimental path entered: '{function}' in '{module}'.",
        "dev_hint": "This path is not part of the stable API surface.",
        "qa_message": "Experimental path: '{function}' in '{module}'.",
        "qa_hint": "Flag this path for API stability review.",
        "agent_message": "Experimental function: '{function}' ({module}).",
        "agent_hint": "Not part of the stable API. Use validated alternatives where available.",
    },
    "MSM-WARN-SEL-001": {
        "title": "Selection warning",
        "user_message": "The selection may be ambiguous or incomplete.",
        "user_hint": "Review the selection string and use a more specific expression. Docs: {doc_url}",
        "dev_message": "Selection warning in '{caller}'.",
        "dev_hint": "Review selection parsing and defaults. Docs: {doc_url}",
        "qa_message": "Selection warning in '{caller}'.",
        "qa_hint": "Review selection parsing and defaults. Docs: {doc_url}",
        "agent_message": "Selection warning in '{caller}'.",
        "agent_hint": "Review selection parsing and defaults. Docs: {doc_url}",
    },
    "MSM-WARN-DEP-001": {
        "title": "Deprecated API",
        "user_message": "This functionality is deprecated.",
        "user_hint": "Check the documentation for the recommended replacement. Docs: {doc_url}",
        "dev_message": "Deprecated API used in '{caller}'.",
        "dev_hint": "Update callsite to the recommended API. Docs: {doc_url}",
        "qa_message": "Deprecated API used in '{caller}'.",
        "qa_hint": "Update callsite to the recommended API. Docs: {doc_url}",
        "agent_message": "Deprecated API used in '{caller}'.",
        "agent_hint": "Update callsite to the recommended API. Docs: {doc_url}",
    },
    "MSM-WARN-STRUCT-001": {
        "title": "Cross-chain covalent bonds",
        "user_message": "Cross-chain covalent bonds were detected.",
        "user_hint": "Verify whether these bonds are expected in your system. Docs: {doc_url}",
        "dev_message": "Cross-chain covalent bonds reported in '{caller}' ({count} pair(s)).",
        "dev_hint": "Verify struct_conn interpretation and chain assignments. Inspect 'pairs' in the diagnostic context. Docs: {doc_url}",
        "qa_message": "Cross-chain covalent bonds reported in '{caller}' ({count} pair(s)).",
        "qa_hint": "Verify struct_conn interpretation and chain assignments. Inspect 'pairs' in the diagnostic context. Docs: {doc_url}",
        "agent_message": "Cross-chain covalent bonds reported in '{caller}' ({count} pair(s)).",
        "agent_hint": "Verify struct_conn interpretation and chain assignments. Docs: {doc_url}",
    },
    "MSM-WARN-DL-001": {
        "title": "Download warning",
        "user_message": "Download warning: {message}",
        "user_hint": "Check the source or retry the download. Docs: {doc_url}",
        "dev_message": "Download warning in '{caller}': {message}",
        "dev_hint": "Check URL, connectivity, and retry policy. Resource: {resource}. Provider: {provider}. Reason: {reason}. Docs: {doc_url}",
        "qa_message": "Download warning in '{caller}': {message}",
        "qa_hint": "Check URL, connectivity, and retry policy. Resource: {resource}. Provider: {provider}. Attempt: {attempt}/{retries}. Reason: {reason}. Docs: {doc_url}",
        "agent_message": "Download warning in '{caller}': {message}",
        "agent_hint": "Check URL, connectivity, and retry policy. Resource: {resource}. Provider: {provider}. Attempt: {attempt}/{retries}. Reason: {reason}. Docs: {doc_url}",
    },
    "MSM-WARN-ARG-001": {
        "title": "Argument not digested",
        "user_message": "Argument '{argument}' was not digested.",
        "user_hint": "Review the argument or check the function documentation. Docs: {doc_url}",
        "dev_message": "Argument '{argument}' was not digested.",
        "dev_hint": "Check argdigest rules or mapping for '{argument}'. Docs: {doc_url}",
        "qa_message": "Argument '{argument}' was not digested.",
        "qa_hint": "Check argdigest rules or mapping for '{argument}'. Docs: {doc_url}",
        "agent_message": "Argument '{argument}' was not digested.",
        "agent_hint": "Check argdigest rules or mapping for '{argument}'. Docs: {doc_url}",
    },
    "MSM-WARN-NB-001": {
        "title": "Numba JIT compilation",
        "user_message": "An uncached Numba kernel is compiling for '{kernel}'. This may take a moment.",
        "user_hint": "Call 'molsysmt.warmup_numba()' to precompile common kernels. Docs: {doc_url}",
        "dev_message": "Uncached Numba JIT compilation triggered in '{module}.{kernel}'.",
        "dev_hint": "Consider precompiling with molsysmt.warmup_numba(). Cache state: {cache_state}. Docs: {doc_url}",
        "qa_message": "Uncached Numba JIT compilation triggered in '{module}.{kernel}'.",
        "qa_hint": "Consider precompiling with molsysmt.warmup_numba(). Cache state: {cache_state}. Docs: {doc_url}",
        "agent_message": "Uncached Numba JIT compilation triggered in '{module}.{kernel}'.",
        "agent_hint": "Consider precompiling with molsysmt.warmup_numba(). Docs: {doc_url}",
    },
    "MSM-WARN-IO-002": {
        "title": "Multiple data containers found",
        "user_message": "The file contains more than one data container; only the first one will be used.",
        "user_hint": "Verify if the file format (e.g., BCIF/CIF) was intended to have multiple entries. Docs: {doc_url}",
        "dev_message": "Multiple DataContainers detected in '{caller}' for file format '{format}'.",
        "dev_hint": "Consider adding support for multi-container selection if needed. Docs: {doc_url}",
        "qa_message": "Multiple DataContainers detected in '{caller}'.",
        "qa_hint": "Verify data integrity for multi-block files. Docs: {doc_url}",
        "agent_message": "Multiple DataContainers detected. Using the first one.",
        "agent_hint": "If multiple blocks are needed, this converter is not suitable. Docs: {doc_url}",
    },
    "MSM-WARN-STRUCT-002": {
        "title": "Ambiguous structure selection",
        "user_message": "The input contains multiple structures, but this operation only supports a single one. Using the first structure (index 0).",
        "user_hint": "Use 'structure_indices' to specify exactly which structure to process. Docs: {doc_url}",
        "dev_message": "Ambiguous structure in '{caller}': received {count} structures, using 0.",
        "dev_hint": "Ensure the caller filters structures or that the converter handles multiple frames. Docs: {doc_url}",
        "qa_message": "Ambiguous structure in '{caller}': received {count} structures, using 0.",
        "qa_hint": "Check if multi-frame support is required for this path. Docs: {doc_url}",
        "agent_message": "Ambiguous structure in '{caller}': received {count} structures, using 0.",
        "agent_hint": "Explicitly select a structure index to avoid this warning. Docs: {doc_url}",
    },
    "MSM-WARN-STRUCT-004": {
        "title": "Molecular system mismatch across models",
        "user_message": "Input models do not share the same molecular system and cannot be merged into one trajectory.",
        "user_hint": "Models will be returned separately. If this is unexpected, validate topology consistency across models. Docs: {doc_url}",
        "dev_message": "Model mismatch in '{caller}': {count} models do not share the same topology, returning separate systems.",
        "dev_hint": "Check atom/residue/entity identity mapping before concatenation. Docs: {doc_url}",
        "qa_message": "Model mismatch in '{caller}': {count} models do not share the same topology. Returning separate systems.",
        "qa_hint": "Validate topology identity consistency across all models. Docs: {doc_url}",
        "agent_message": "{count} models have incompatible molecular systems. Returned as separate systems.",
        "agent_hint": "Normalize model topology before merging.",
    },
    "MSM-INFO-EXP-001": {
        "title": "Experimental path",
        "user_message": "The path '{module}.{function}' is experimental. {custom_message}",
        "user_hint": "Use with caution in production. Stability is not guaranteed for version 1.0.0. Docs: {doc_url}",
        "dev_message": "Experimental path '{module}.{function}' accessed by '{caller}'.",
        "dev_hint": "Excluded from 1.0 support contract. Custom note: {custom_message}. Docs: {doc_url}",
        "qa_message": "Experimental path '{module}.{function}' accessed.",
        "qa_hint": "Verify stability. Docs: {doc_url}",
        "agent_message": "Path '{module}.{function}' is experimental.",
        "agent_hint": "Stability not guaranteed.",
    },
    "MSM-ERR-ARG-001": {
        "title": "Argument error",
        "user_message": "Error in argument '{argument}' with value '{value}'.",
        "user_hint": "Check the API for the expected argument format. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "dev_hint": "Validate inputs and update docs if needed. Docs: {doc_url} | Issues: {issues_url}",
        "qa_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "qa_hint": "Validate inputs and update docs if needed. Docs: {doc_url} | Issues: {issues_url}",
        "agent_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "agent_hint": "Validate inputs and update docs if needed. Docs: {doc_url} | Issues: {issues_url}",
    },
    "MSM-ERR-ARG-002": {
        "title": "Invalid argument choice",
        "user_message": "The value '{value}' is not valid for argument '{argument}'.",
        "user_hint": "Valid options are: {choices}. Docs: {doc_url}",
        "dev_message": "Invalid choice for '{argument}' in '{caller}'. Got '{value}'.",
        "dev_hint": "Ensure input matches allowed set: {choices}. Docs: {doc_url}",
        "qa_message": "Invalid choice for '{argument}' in '{caller}'.",
        "qa_hint": "Check enum constraints. Docs: {doc_url}",
        "agent_message": "Invalid value for '{argument}'.",
        "agent_hint": "Retry with one of: {choices}.",
    },
    "MSM-ERR-ARG-003": {
        "title": "Argument length mismatch",
        "user_message": "Length mismatch for argument '{argument}'. Expected {expected}, got {actual}.",
        "user_hint": "Ensure the list/array length matches the target dimension. Docs: {doc_url}",
        "dev_message": "Length mismatch in '{caller}' for '{argument}'. Expected {expected}, got {actual}.",
        "dev_hint": "Validate consistency between parallel input lists. Docs: {doc_url}",
        "qa_message": "Length mismatch in '{caller}' for '{argument}'.",
        "qa_hint": "Validate input dimensions. Docs: {doc_url}",
        "agent_message": "Length mismatch for argument '{argument}'.",
        "agent_hint": "Adjust the list length to match the target context ({expected}).",
    },
    "MSM-ERR-ARG-004": {
        "title": "Argument conflict",
        "user_message": "Arguments '{arg1}' and '{arg2}' cannot be used together or are missing.",
        "user_hint": "Check the documentation for mutually exclusive or required arguments. Docs: {doc_url}",
        "dev_message": "Conflict between '{arg1}' and '{arg2}' in '{caller}'. Reason: {reason}.",
        "dev_hint": "Enforce argument logic. Docs: {doc_url}",
        "qa_message": "Argument conflict in '{caller}'.",
        "qa_hint": "Check parameter matrix. Docs: {doc_url}",
        "agent_message": "Conflict between arguments '{arg1}' and '{arg2}'.",
        "agent_hint": "Use one or the other, or provide the missing one.",
    },
    "MSM-ERR-STRUCT-003": {
        "title": "Structural inconsistency",
        "user_message": "Structural inconsistency detected: {reason}.",
        "user_hint": "Ensure that the atoms, residues, or frames match between the systems being compared or merged. Docs: {doc_url}",
        "dev_message": "Structural inconsistency in '{caller}': {reason}.",
        "dev_hint": "Check alignment or dimensions. Docs: {doc_url}",
        "qa_message": "Structural inconsistency in '{caller}'.",
        "qa_hint": "Check alignment or dimensions. Docs: {doc_url}",
        "agent_message": "Structural inconsistency detected.",
        "agent_hint": "Ensure atom/frame counts match ({reason}).",
    },
    "MSM-ERR-INT-001": {
        "title": "Internal algorithm error",
        "user_message": "An internal error occurred in the algorithm.",
        "user_hint": "This indicates a bug or an unexpected state. Please report it. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Internal error in '{caller}': {reason}.",
        "dev_hint": "Debug the algorithm state. Issues: {issues_url}",
        "qa_message": "Internal error in '{caller}'.",
        "qa_hint": "Debug the algorithm state. Issues: {issues_url}",
        "agent_message": "Internal algorithm error.",
        "agent_hint": "Report this issue. The internal state is inconsistent.",
    },
    "MSM-ERR-ITER-001": {
        "title": "Iterator error",
        "user_message": "Errors were found in iterator arguments.",
        "user_hint": "Review the arguments and the iterator type. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Iterator argument error in '{caller}'.",
        "dev_hint": "Review iterator arguments and validation. Docs: {doc_url}",
        "qa_message": "Iterator argument error in '{caller}'.",
        "qa_hint": "Review iterator arguments and validation. Docs: {doc_url}",
        "agent_message": "Iterator argument error in '{caller}'.",
        "agent_hint": "Review iterator arguments and validation. Docs: {doc_url}",
    },
    "MSM-ERR-DEP-001": {
        "title": "Missing library",
        "user_message": "Library '{library}' is not installed.",
        "user_hint": "Install '{library}' to use this functionality. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Missing library '{library}' required by '{caller}'.",
        "dev_hint": "Add dependency or guard optional path. Issues: {issues_url}",
        "qa_message": "Missing library '{library}' required by '{caller}'.",
        "qa_hint": "Add dependency or guard optional path. Issues: {issues_url}",
        "agent_message": "Missing library '{library}' required by '{caller}'.",
        "agent_hint": "Add dependency or guard optional path. Issues: {issues_url}",
    },
    "MSM-ERR-SYS-001": {
        "title": "Molecular system required",
        "user_message": "A molecular system is required for this operation.",
        "user_hint": "Provide a valid molecular system. Docs: {doc_url}",
        "dev_message": "Molecular system required in '{caller}'.",
        "dev_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "qa_message": "Molecular system required in '{caller}'.",
        "qa_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "agent_message": "Molecular system required in '{caller}'.",
        "agent_hint": "Validate inputs and update error handling. Docs: {doc_url}",
    },
    "MSM-ERR-SYS-002": {
        "title": "Multiple molecular systems required",
        "user_message": "Multiple molecular systems are required for this operation.",
        "user_hint": "Provide a list or set of molecular systems. Docs: {doc_url}",
        "dev_message": "Multiple molecular systems required in '{caller}'.",
        "dev_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "qa_message": "Multiple molecular systems required in '{caller}'.",
        "qa_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "agent_message": "Multiple molecular systems required in '{caller}'.",
        "agent_hint": "Validate inputs and update error handling. Docs: {doc_url}",
    },
    "MSM-ERR-CONV-001": {
        "title": "Incompatible conversion",
        "user_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "user_hint": "Check required attributes: {missing_arguments}. Docs: {doc_url}",
        "dev_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "dev_hint": "Ensure required attributes are provided: {missing_arguments}. Docs: {doc_url}",
        "qa_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "qa_hint": "Ensure required attributes are provided: {missing_arguments}. Docs: {doc_url}",
        "agent_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "agent_hint": "Ensure required attributes are provided: {missing_arguments}. Docs: {doc_url}",
    },
    "MSM-ERR-CONV-002": {
        "title": "Conversion not implemented",
        "user_message": "No conversion implemented from '{from_form}' to '{to_form}'.",
        "user_hint": "Check the documentation for available conversions. Docs: {doc_url}",
        "dev_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "dev_hint": "Implement conversion or document unsupported path. Docs: {doc_url}",
        "qa_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "qa_hint": "Implement conversion or document unsupported path. Docs: {doc_url}",
        "agent_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "agent_hint": "Implement conversion or document unsupported path. Docs: {doc_url}",
    },
    "MSM-ERR-ITER-002": {
        "title": "Iterator not implemented",
        "user_message": "Iterator not implemented for form '{form}'.",
        "user_hint": "Switch form or use another compatible function. Docs: {doc_url}",
        "dev_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "dev_hint": "Implement iterator or document unsupported form. Docs: {doc_url}",
        "qa_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "qa_hint": "Implement iterator or document unsupported form. Docs: {doc_url}",
        "agent_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "agent_hint": "Implement iterator or document unsupported form. Docs: {doc_url}",
    },
    "MSM-ERR-METHOD-001": {
        "title": "Method not implemented",
        "user_message": "This method is not implemented yet.",
        "user_hint": "Check alternative methods or wait for an update. Docs: {doc_url}",
        "dev_message": "Method '{method}' not implemented in '{caller}'.",
        "dev_hint": "Implement method or document missing functionality. Arguments: {arguments}. Docs: {doc_url}",
        "qa_message": "Method '{method}' not implemented in '{caller}'.",
        "qa_hint": "Implement method or document missing functionality. Arguments: {arguments}. Docs: {doc_url}",
        "agent_message": "Method '{method}' not implemented in '{caller}'.",
        "agent_hint": "Implement method or document missing functionality. Docs: {doc_url}",
    },
    "MSM-ERR-FORM-001": {
        "title": "Form not supported",
        "user_message": "Form '{form}' is not supported by '{caller}'.",
        "user_hint": "Switch form or use another compatible function. Docs: {doc_url}",
        "dev_message": "Form '{form}' not supported in '{caller}'.",
        "dev_hint": "Implement support or document constraints. Docs: {doc_url}",
        "qa_message": "Form '{form}' not supported in '{caller}'.",
        "qa_hint": "Implement support or document constraints. Docs: {doc_url}",
        "agent_message": "Form '{form}' not supported in '{caller}'.",
        "agent_hint": "Implement support or document constraints. Docs: {doc_url}",
    },
    "MSM-ERR-SYNTAX-001": {
        "title": "Syntax not supported",
        "user_message": "Syntax '{syntax}' is not supported by '{caller}'.",
        "user_hint": "Check documentation for supported syntax. Docs: {doc_url}",
        "dev_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "dev_hint": "Implement support or document constraints. Docs: {doc_url}",
        "qa_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "qa_hint": "Implement support or document constraints. Docs: {doc_url}",
        "agent_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "agent_hint": "Implement support or document constraints. Docs: {doc_url}",
    },
    "MSM-ERR-FORM-002": {
        "title": "Form not allowed",
        "user_message": "The form '{form}' does not provide '{requested_attribute}' in '{caller}'.",
        "user_hint": "Use a compatible form or convert first. Docs: {doc_url}",
        "dev_message": "Form '{form}' does not provide '{requested_attribute}' in '{caller}'.",
        "dev_hint": "Implement support, route through conversion, or document the limitation. Docs: {doc_url}",
        "qa_message": "Form '{form}' does not provide '{requested_attribute}' in '{caller}'.",
        "qa_hint": "Implement support, route through conversion, or document the limitation. Docs: {doc_url}",
        "agent_message": "Form '{form}' does not provide '{requested_attribute}' in '{caller}'.",
        "agent_hint": "Implement support or document constraints. Docs: {doc_url}",
    },
    "MSM-ERR-IO-001": {
        "title": "File already handled",
        "user_message": "File '{filename}' is already handled by MolSysMT.",
        "user_hint": "Avoid registering the same file twice. Docs: {doc_url}",
        "dev_message": "File '{filename}' already handled.",
        "dev_hint": "Check file registry and duplicate handling. Docs: {doc_url}",
        "qa_message": "File '{filename}' already handled.",
        "qa_hint": "Check file registry and duplicate handling. Docs: {doc_url}",
        "agent_message": "File '{filename}' already handled.",
        "agent_hint": "Check file registry and duplicate handling. Docs: {doc_url}",
    },
    "MSM-ERR-IO-002": {
        "title": "Invalid file content",
        "user_message": "The file content violates the format standard: {reason}.",
        "user_hint": "Check the file source or validate its format. Docs: {doc_url}",
        "dev_message": "Format violation in '{caller}': {reason}. Record: {record}. File: {filename}.",
        "dev_hint": "Check parser logic and upstream file integrity. Docs: {doc_url}",
        "qa_message": "Invalid file content in '{caller}': {reason}. Record: {record}. File: {filename}.",
        "qa_hint": "Check parser logic and upstream file integrity. Docs: {doc_url}",
        "agent_message": "Invalid file content in '{caller}': {reason}. Record: {record}. File: {filename}.",
        "agent_hint": "The file does not follow the expected standard. Check if it is corrupted or incomplete. Docs: {doc_url}",
    },
    "MSM-INFO-HVY-001": {
        "title": "Heavy trajectory path selected",
        "user_message": "Processing '{operation}' on '{form}' in heavy (chunked) mode. Estimated footprint: {footprint_bytes} bytes (budget: {max_ram_usage} bytes).",
        "user_hint": "Heavy mode processes the trajectory in chunks to avoid memory exhaustion. Progress will be reported through telemetry.",
        "dev_message": "Heavy path activated for '{operation}' on '{form}'. Footprint estimate: {footprint_bytes} bytes. Budget: {max_ram_usage} bytes.",
        "dev_hint": "Verify that the reducer and iterator are correctly matched to this form.",
        "qa_message": "Heavy path selected for '{operation}' on '{form}'. Footprint: {footprint_bytes} bytes, budget: {max_ram_usage} bytes.",
        "qa_hint": "Confirm that the chunked path produces results identical to the eager path for this operation.",
        "agent_message": "Heavy (chunked) path selected for '{operation}' on '{form}'. Footprint: {footprint_bytes} bytes.",
        "agent_hint": "Verify reducer/iterator pairing for this form. Budget: {max_ram_usage} bytes.",
    },
    "MSM-INFO-HVY-002": {
        "title": "Eager path accepted",
        "user_message": "Processing '{operation}' in eager (in-memory) mode. Estimated footprint: {footprint_bytes} bytes.",
        "user_hint": "The estimated memory footprint is within the configured budget. The trajectory will be loaded fully into memory.",
        "dev_message": "Eager path accepted for '{operation}'. Footprint estimate: {footprint_bytes} bytes is within budget.",
        "dev_hint": "No chunked processing required. The full trajectory fits in the configured RAM budget.",
        "qa_message": "Eager path accepted for '{operation}'. Footprint: {footprint_bytes} bytes.",
        "qa_hint": "Confirm that the eager path produces correct results for this operation.",
        "agent_message": "Eager (in-memory) path accepted for '{operation}'. Footprint: {footprint_bytes} bytes.",
        "agent_hint": "Footprint is within the configured RAM budget. No chunking needed.",
    },
    "MSM-WARN-HVY-001": {
        "title": "Slow chunk I/O detected",
        "user_message": "Chunk {chunk_index} took {io_time_s:.2f} seconds to process. I/O may be a bottleneck.",
        "user_hint": "Consider using a faster storage device or reducing the chunk size to improve throughput.",
        "dev_message": "Slow chunk I/O at chunk {chunk_index}: {io_time_s:.2f} seconds elapsed.",
        "dev_hint": "Profile the iterator and reducer for this chunk to identify the bottleneck.",
        "qa_message": "Slow chunk I/O at chunk {chunk_index}: {io_time_s:.2f} seconds.",
        "qa_hint": "Verify that this is expected for the test data size and storage backend.",
        "agent_message": "Slow I/O detected at chunk {chunk_index} ({io_time_s:.2f} s).",
        "agent_hint": "Check storage throughput. Consider smaller chunks or a faster backend.",
    },
    "MSM-WARN-HVY-003": {
        "title": "Memory pressure during heavy processing",
        "user_message": "RAM usage ({rss_bytes} bytes) has exceeded {pressure_pct:.0f}% of the configured budget ({budget_bytes} bytes) at chunk {chunk_index}.",
        "user_hint": "Consider reducing chunk_size, freeing memory, or increasing molsysmt.configure.max_ram_usage.",
        "dev_message": "Memory pressure at chunk {chunk_index}: RSS={rss_bytes} bytes, budget={budget_bytes} bytes ({pressure_pct:.1f}% used).",
        "dev_hint": "Investigate reducer accumulation and temporary allocations. Reducing chunk_size lowers peak memory per chunk.",
        "qa_message": "Memory pressure at chunk {chunk_index}: RSS={rss_bytes} bytes.",
        "qa_hint": "Ensure test fixtures do not exhaust memory in CI.",
        "agent_message": "Memory pressure at chunk {chunk_index}: {rss_bytes} bytes RSS / {budget_bytes} bytes budget.",
        "agent_hint": "Reduce chunk_size or free memory before continuing.",
    },
    "MSM-WARN-HVY-002": {
        "title": "Corrupt frame skipped",
        "user_message": "Frame {frame_index} in chunk {chunk_index} could not be read and was skipped. Reason: {reason}.",
        "user_hint": "The trajectory file may be partially corrupted. Verify the source file integrity.",
        "dev_message": "Corrupt frame at chunk {chunk_index}, frame {frame_index}: {reason}. Frame skipped.",
        "dev_hint": "Check the iterator and underlying file reader for error propagation at this frame.",
        "qa_message": "Corrupt frame skipped at chunk {chunk_index}, frame {frame_index}. Reason: {reason}.",
        "qa_hint": "Verify that skipping corrupt frames does not silently bias analysis results.",
        "agent_message": "Frame {frame_index} (chunk {chunk_index}) skipped: {reason}.",
        "agent_hint": "Inspect the source file around this frame for corruption.",
    },
    "MSM-ERR-HVY-001": {
        "title": "Unsupported heavy-mode combination",
        "user_message": "Operation '{operation}' is not supported in heavy mode for form '{form}'. Reason: {reason}.",
        "user_hint": "Switch to an eager (in-memory) approach or use a supported form. Docs: {doc_url}",
        "dev_message": "Unsupported heavy-mode combination: operation='{operation}', form='{form}'. Reason: {reason}.",
        "dev_hint": "Implement heavy-mode support for this operation/form pair or document the limitation. Docs: {doc_url}",
        "qa_message": "Unsupported heavy-mode combination: operation='{operation}', form='{form}'.",
        "qa_hint": "Verify that all Tier 1 heavy operations are covered for this form. Docs: {doc_url}",
        "agent_message": "Unsupported heavy-mode: operation='{operation}', form='{form}'. Reason: {reason}.",
        "agent_hint": "Implement or redirect to an eager path. Docs: {doc_url}",
    },
    "MSM-ERR-HVY-002": {
        "title": "Heavy output persistence failure",
        "user_message": "Cannot persist the heavy-mode output. Reason: {reason}.",
        "user_hint": "Free disk space or reduce the output size. Docs: {doc_url}",
        "dev_message": "Heavy output persistence failure. Reason: {reason}. Predicted: {predicted_bytes} bytes. Available: {available_bytes} bytes.",
        "dev_hint": "Check disk budget before writing. Adjust chunk size or output path. Docs: {doc_url}",
        "qa_message": "Heavy output persistence failure. Reason: {reason}.",
        "qa_hint": "Ensure the test environment has sufficient disk space for heavy-mode outputs. Docs: {doc_url}",
        "agent_message": "Heavy output persistence failed: {reason}. Predicted: {predicted_bytes} bytes, available: {available_bytes} bytes.",
        "agent_hint": "Check disk space. Reduce output size or change the output path.",
    },
}

SIGNALS = {
    "molsysmt.warning.selection": {"extra_required": ["caller"]},
    "molsysmt.warning.deprecation": {"extra_required": ["caller"]},
    "molsysmt.warning.cross_chain_bonds": {"extra_required": ["caller", "count", "pairs"]},
    "molsysmt.warning.download": {"extra_required": ["caller"]},
    "molsysmt.warning.not_digested": {"extra_required": ["argument"]},
    "molsysmt.warning.numba_jit": {"extra_required": ["kernel", "module"]},
    "molsysmt.warning.multi_container": {"extra_required": ["caller", "format"]},
    "molsysmt.warning.ambiguous_structure": {"extra_required": ["caller", "count"]},
    "molsysmt.warning.molecular_system_mismatch": {"extra_required": ["caller"]},
    "molsysmt.info.experimental": {"extra_required": ["module", "function", "custom_message", "caller"]},
    "molsysmt.error.argument": {"extra_required": ["argument", "value", "caller"]},
    "molsysmt.error.argument.choice": {"extra_required": ["argument", "value", "choices", "caller"]},
    "molsysmt.error.argument.length": {"extra_required": ["argument", "expected", "actual", "caller"]},
    "molsysmt.error.argument.conflict": {"extra_required": ["arg1", "arg2", "reason", "caller"]},
    "molsysmt.error.structure.inconsistency": {"extra_required": ["reason", "caller"]},
    "molsysmt.error.internal.algorithm": {"extra_required": ["reason", "caller"]},
    "molsysmt.error.iterator": {"extra_required": ["caller"]},
    "molsysmt.error.library_not_found": {"extra_required": ["library", "caller"]},
    "molsysmt.error.molecular_system_needed": {"extra_required": ["caller"]},
    "molsysmt.error.molecular_systems_needed": {"extra_required": ["caller"]},
    "molsysmt.error.not_compatible_conversion": {"extra_required": ["from_form", "to_form", "missing_arguments"]},
    "molsysmt.error.not_implemented_conversion": {"extra_required": ["from_form", "to_form", "caller"]},
    "molsysmt.error.not_implemented_iterator": {"extra_required": ["form", "caller"]},
    "molsysmt.error.not_implemented_method": {"extra_required": ["caller"]},
    "molsysmt.error.not_supported_form": {"extra_required": ["form", "caller"]},
    "molsysmt.error.not_supported_syntax": {"extra_required": ["syntax", "caller"]},
    "molsysmt.error.not_with_this_form": {"extra_required": ["caller"]},
    "molsysmt.error.file_already_handled": {"extra_required": ["filename"]},
    "molsysmt.error.file_content": {"extra_required": ["reason", "caller"]},
    "molsysmt.info.heavy.path_selected": {"extra_required": ["operation", "form", "footprint_bytes", "max_ram_usage"]},
    "molsysmt.info.heavy.eager_accepted": {"extra_required": ["operation", "footprint_bytes"]},
    "molsysmt.info.heavy.chunk_processed": {"extra_required": ["operation", "chunk_index", "n_chunks", "elapsed_s", "eta_s"]},
    "molsysmt.warning.heavy.slow_io": {"extra_required": ["chunk_index", "io_time_s"]},
    "molsysmt.warning.heavy.corrupt_frame": {"extra_required": ["chunk_index", "frame_index", "reason"]},
    "molsysmt.warning.heavy.memory_pressure": {"extra_required": ["chunk_index", "rss_bytes", "budget_bytes", "pressure_pct"]},
    "molsysmt.error.heavy.unsupported_operation": {"extra_required": ["operation", "form", "reason"]},
    "molsysmt.error.heavy.output_failure": {"extra_required": ["reason"]},
}
