from __future__ import annotations

from pathlib import Path

from .meta import DOC_URL, ISSUES_URL, API_URL

PACKAGE_ROOT = Path(__file__).resolve().parents[2]

META = {
    "doc_url": DOC_URL,
    "issues_url": ISSUES_URL,
    "api_url": API_URL,
}

CATALOG = {
    "warnings": {
        "SelectionWarning": {
            "code": "MSM-WARN-SEL-001",
            "source": "molsysmt.warning.selection",
            "category": "selection",
            "level": "WARNING",
        },
        "MolSysMTDeprecationWarning": {
            "code": "MSM-WARN-DEP-001",
            "source": "molsysmt.warning.deprecation",
            "category": "deprecation",
            "level": "WARNING",
        },
        "CrossChainCovalentBondsWarning": {
            "code": "MSM-WARN-STRUCT-001",
            "source": "molsysmt.warning.cross_chain_bonds",
            "category": "structure",
            "level": "WARNING",
        },
        "DownloadWarning": {
            "code": "MSM-WARN-DL-001",
            "source": "molsysmt.warning.download",
            "category": "io",
            "level": "WARNING",
        },
        "NotDigestedArgumentWarning": {
            "code": "MSM-WARN-ARG-001",
            "source": "molsysmt.warning.not_digested",
            "category": "argument",
            "level": "WARNING",
        },
        "NumbaJitWarning": {
            "code": "MSM-WARN-NB-001",
            "source": "molsysmt.warning.numba_jit",
            "category": "performance",
            "level": "WARNING",
        },
        "MultiContainerWarning": {
            "code": "MSM-WARN-IO-002",
            "source": "molsysmt.warning.multi_container",
            "category": "io",
            "level": "WARNING",
        },
        "AmbiguousStructureWarning": {
            "code": "MSM-WARN-STRUCT-002",
            "source": "molsysmt.warning.ambiguous_structure",
            "category": "structure",
            "level": "WARNING",
        },
    },
    "exceptions": {
        "ArgumentError": {
            "code": "MSM-ERR-ARG-001",
            "source": "molsysmt.error.argument",
            "category": "argument",
            "level": "ERROR",
        },
        "ArgumentChoiceError": {
            "code": "MSM-ERR-ARG-002",
            "source": "molsysmt.error.argument.choice",
            "category": "argument",
            "level": "ERROR",
        },
        "ArgumentLengthError": {
            "code": "MSM-ERR-ARG-003",
            "source": "molsysmt.error.argument.length",
            "category": "argument",
            "level": "ERROR",
        },
        "ArgumentConflictError": {
            "code": "MSM-ERR-ARG-004",
            "source": "molsysmt.error.argument.conflict",
            "category": "argument",
            "level": "ERROR",
        },
        "StructuralInconsistencyError": {
            "code": "MSM-ERR-STRUCT-003",
            "source": "molsysmt.error.structure.inconsistency",
            "category": "structure",
            "level": "ERROR",
        },
        "InternalAlgorithmError": {
            "code": "MSM-ERR-INT-001",
            "source": "molsysmt.error.internal.algorithm",
            "category": "internal",
            "level": "ERROR",
        },
        "IteratorError": {
            "code": "MSM-ERR-ITER-001",
            "source": "molsysmt.error.iterator",
            "category": "iterator",
            "level": "ERROR",
        },
        "LibraryNotFoundError": {
            "code": "MSM-ERR-DEP-001",
            "source": "molsysmt.error.library_not_found",
            "category": "dependency",
            "level": "ERROR",
        },
        "MolecularSystemNeededError": {
            "code": "MSM-ERR-SYS-001",
            "source": "molsysmt.error.molecular_system_needed",
            "category": "system",
            "level": "ERROR",
        },
        "MolecularSystemsNeededError": {
            "code": "MSM-ERR-SYS-002",
            "source": "molsysmt.error.molecular_systems_needed",
            "category": "system",
            "level": "ERROR",
        },
        "NotCompatibleConversionError": {
            "code": "MSM-ERR-CONV-001",
            "source": "molsysmt.error.not_compatible_conversion",
            "category": "conversion",
            "level": "ERROR",
        },
        "NotImplementedConversionError": {
            "code": "MSM-ERR-CONV-002",
            "source": "molsysmt.error.not_implemented_conversion",
            "category": "conversion",
            "level": "ERROR",
        },
        "NotImplementedIteratorError": {
            "code": "MSM-ERR-ITER-002",
            "source": "molsysmt.error.not_implemented_iterator",
            "category": "iterator",
            "level": "ERROR",
        },
        "NotImplementedMethodError": {
            "code": "MSM-ERR-METHOD-001",
            "source": "molsysmt.error.not_implemented_method",
            "category": "not_implemented",
            "level": "ERROR",
        },
        "NotSupportedFormError": {
            "code": "MSM-ERR-FORM-001",
            "source": "molsysmt.error.not_supported_form",
            "category": "not_supported",
            "level": "ERROR",
        },
        "NotSupportedSyntaxError": {
            "code": "MSM-ERR-SYNTAX-001",
            "source": "molsysmt.error.not_supported_syntax",
            "category": "not_supported",
            "level": "ERROR",
        },
        "NotWithThisFormError": {
            "code": "MSM-ERR-FORM-002",
            "source": "molsysmt.error.not_with_this_form",
            "category": "not_supported",
            "level": "ERROR",
        },
        "FileAlreadyHandledError": {
            "code": "MSM-ERR-IO-001",
            "source": "molsysmt.error.file_already_handled",
            "category": "io",
            "level": "ERROR",
        },
    },
}

CODES = {
    "MSM-WARN-SEL-001": {
        "title": "Selection warning",
        "user_message": "The selection may be ambiguous or incomplete.",
        "user_hint": "Review the selection string and use a more specific expression. Docs: {doc_url}",
        "dev_message": "Selection warning in '{caller}'.",
        "dev_hint": "Review selection parsing and defaults. Docs: {doc_url}",
        "qa_message": "Selection warning in '{caller}'.",
        "qa_hint": "Review selection parsing and defaults. Docs: {doc_url}",
        "agent_message": "Selection warning in '{caller}'.",
        "agent_hint": "Review selection parsing and defaults. Docs: {doc_url}",
    },
    "MSM-WARN-DEP-001": {
        "title": "Deprecated API",
        "user_message": "This functionality is deprecated.",
        "user_hint": "Check the documentation for the recommended replacement. Docs: {doc_url}",
        "dev_message": "Deprecated API used in '{caller}'.",
        "dev_hint": "Update callsite to the recommended API. Docs: {doc_url}",
        "qa_message": "Deprecated API used in '{caller}'.",
        "qa_hint": "Update callsite to the recommended API. Docs: {doc_url}",
        "agent_message": "Deprecated API used in '{caller}'.",
        "agent_hint": "Update callsite to the recommended API. Docs: {doc_url}",
    },
    "MSM-WARN-STRUCT-001": {
        "title": "Cross-chain covalent bonds",
        "user_message": "Cross-chain covalent bonds were detected.",
        "user_hint": "Verify whether these bonds are expected in your system. Docs: {doc_url}",
        "dev_message": "Cross-chain covalent bonds reported in '{caller}'.",
        "dev_hint": "Verify struct_conn interpretation and chain assignments. Docs: {doc_url}",
        "qa_message": "Cross-chain covalent bonds reported in '{caller}'.",
        "qa_hint": "Verify struct_conn interpretation and chain assignments. Docs: {doc_url}",
        "agent_message": "Cross-chain covalent bonds reported in '{caller}'.",
        "agent_hint": "Verify struct_conn interpretation and chain assignments. Docs: {doc_url}",
    },
    "MSM-WARN-DL-001": {
        "title": "Download warning",
        "user_message": "A warning occurred during download.",
        "user_hint": "Check the source or retry the download. Docs: {doc_url}",
        "dev_message": "Download warning in '{caller}'.",
        "dev_hint": "Check URL, connectivity, and retry policy. Docs: {doc_url}",
        "qa_message": "Download warning in '{caller}'.",
        "qa_hint": "Check URL, connectivity, and retry policy. Docs: {doc_url}",
        "agent_message": "Download warning in '{caller}'.",
        "agent_hint": "Check URL, connectivity, and retry policy. Docs: {doc_url}",
    },
    "MSM-WARN-ARG-001": {
        "title": "Argument not digested",
        "user_message": "Argument '{argument}' was not digested.",
        "user_hint": "Review the argument or check the function documentation. Docs: {doc_url}",
        "dev_message": "Argument '{argument}' was not digested.",
        "dev_hint": "Check argdigest rules or mapping for '{argument}'. Docs: {doc_url}",
        "qa_message": "Argument '{argument}' was not digested.",
        "qa_hint": "Check argdigest rules or mapping for '{argument}'. Docs: {doc_url}",
        "agent_message": "Argument '{argument}' was not digested.",
        "agent_hint": "Check argdigest rules or mapping for '{argument}'. Docs: {doc_url}",
    },
    "MSM-WARN-NB-001": {
        "title": "Numba JIT compilation",
        "user_message": "A Numba kernel is compiling for '{kernel}'. This may take a moment.",
        "user_hint": "Call 'molsysmt.warmup_numba()' to precompile common kernels. Docs: {doc_url}",
        "dev_message": "Numba JIT compilation triggered in '{module}.{kernel}'.",
        "dev_hint": "Consider precompiling with molsysmt.warmup_numba(). Docs: {doc_url}",
        "qa_message": "Numba JIT compilation triggered in '{module}.{kernel}'.",
        "qa_hint": "Consider precompiling with molsysmt.warmup_numba(). Docs: {doc_url}",
        "agent_message": "Numba JIT compilation triggered in '{module}.{kernel}'.",
        "agent_hint": "Consider precompiling with molsysmt.warmup_numba(). Docs: {doc_url}",
    },
    "MSM-WARN-IO-002": {
        "title": "Multiple data containers found",
        "user_message": "The file contains more than one data container; only the first one will be used.",
        "user_hint": "Verify if the file format (e.g., BCIF/CIF) was intended to have multiple entries. Docs: {doc_url}",
        "dev_message": "Multiple DataContainers detected in '{caller}' for file format '{format}'.",
        "dev_hint": "Consider adding support for multi-container selection if needed. Docs: {doc_url}",
        "qa_message": "Multiple DataContainers detected in '{caller}'.",
        "qa_hint": "Verify data integrity for multi-block files. Docs: {doc_url}",
        "agent_message": "Multiple DataContainers detected. Using the first one.",
        "agent_hint": "If multiple blocks are needed, this converter is not suitable. Docs: {doc_url}",
    },
    "MSM-WARN-STRUCT-002": {
        "title": "Ambiguous structure selection",
        "user_message": "The input contains multiple structures, but this operation only supports a single one. Using the first structure (index 0).",
        "user_hint": "Use 'structure_indices' to specify exactly which structure to process. Docs: {doc_url}",
        "dev_message": "Ambiguous structure in '{caller}': received {count} structures, using 0.",
        "dev_hint": "Ensure the caller filters structures or that the converter handles multiple frames. Docs: {doc_url}",
        "qa_message": "Ambiguous structure in '{caller}'.",
        "qa_hint": "Check if multi-frame support is required for this path. Docs: {doc_url}",
        "agent_message": "Ambiguous structure. Defaulting to first frame.",
        "agent_hint": "Explicitly select a structure index to avoid this warning. Docs: {doc_url}",
    },
    "MSM-ERR-ARG-001": {
        "title": "Argument error",
        "user_message": "Error in argument '{argument}' with value '{value}'.",
        "user_hint": "Check the API for the expected argument format. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "dev_hint": "Validate inputs and update docs if needed. Docs: {doc_url} | Issues: {issues_url}",
        "qa_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "qa_hint": "Validate inputs and update docs if needed. Docs: {doc_url} | Issues: {issues_url}",
        "agent_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "agent_hint": "Validate inputs and update docs if needed. Docs: {doc_url} | Issues: {issues_url}",
    },
    "MSM-ERR-ARG-002": {
        "title": "Invalid argument choice",
        "user_message": "The value '{value}' is not valid for argument '{argument}'.",
        "user_hint": "Valid options are: {choices}. Docs: {doc_url}",
        "dev_message": "Invalid choice for '{argument}' in '{caller}'. Got '{value}'.",
        "dev_hint": "Ensure input matches allowed set: {choices}. Docs: {doc_url}",
        "qa_message": "Invalid choice for '{argument}' in '{caller}'.",
        "qa_hint": "Check enum constraints. Docs: {doc_url}",
        "agent_message": "Invalid value for '{argument}'.",
        "agent_hint": "Retry with one of: {choices}.",
    },
    "MSM-ERR-ARG-003": {
        "title": "Argument length mismatch",
        "user_message": "Length mismatch for argument '{argument}'. Expected {expected}, got {actual}.",
        "user_hint": "Ensure the list/array length matches the target dimension. Docs: {doc_url}",
        "dev_message": "Length mismatch in '{caller}' for '{argument}'. Expected {expected}, got {actual}.",
        "dev_hint": "Validate consistency between parallel input lists. Docs: {doc_url}",
        "qa_message": "Length mismatch in '{caller}' for '{argument}'.",
        "qa_hint": "Validate input dimensions. Docs: {doc_url}",
        "agent_message": "Length mismatch for argument '{argument}'.",
        "agent_hint": "Adjust the list length to match the target context ({expected}).",
    },
    "MSM-ERR-ARG-004": {
        "title": "Argument conflict",
        "user_message": "Arguments '{arg1}' and '{arg2}' cannot be used together or are missing.",
        "user_hint": "Check the documentation for mutually exclusive or required arguments. Docs: {doc_url}",
        "dev_message": "Conflict between '{arg1}' and '{arg2}' in '{caller}'. Reason: {reason}.",
        "dev_hint": "Enforce argument logic. Docs: {doc_url}",
        "qa_message": "Argument conflict in '{caller}'.",
        "qa_hint": "Check parameter matrix. Docs: {doc_url}",
        "agent_message": "Conflict between arguments '{arg1}' and '{arg2}'.",
        "agent_hint": "Use one or the other, or provide the missing one.",
    },
    "MSM-ERR-STRUCT-003": {
        "title": "Structural inconsistency",
        "user_message": "Structural inconsistency detected: {reason}.",
        "user_hint": "Ensure that the atoms, residues, or frames match between the systems being compared or merged. Docs: {doc_url}",
        "dev_message": "Structural inconsistency in '{caller}': {reason}.",
        "dev_hint": "Check alignment or dimensions. Docs: {doc_url}",
        "qa_message": "Structural inconsistency in '{caller}'.",
        "qa_hint": "Check alignment or dimensions. Docs: {doc_url}",
        "agent_message": "Structural inconsistency detected.",
        "agent_hint": "Ensure atom/frame counts match ({reason}).",
    },
    "MSM-ERR-INT-001": {
        "title": "Internal algorithm error",
        "user_message": "An internal error occurred in the algorithm.",
        "user_hint": "This indicates a bug or an unexpected state. Please report it. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Internal error in '{caller}': {reason}.",
        "dev_hint": "Debug the algorithm state. Issues: {issues_url}",
        "qa_message": "Internal error in '{caller}'.",
        "qa_hint": "Debug the algorithm state. Issues: {issues_url}",
        "agent_message": "Internal algorithm error.",
        "agent_hint": "Report this issue. The internal state is inconsistent.",
    },
    "MSM-ERR-ITER-001": {
        "title": "Iterator error",
        "user_message": "Errors were found in iterator arguments.",
        "user_hint": "Review the arguments and the iterator type. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Iterator argument error in '{caller}'.",
        "dev_hint": "Review iterator arguments and validation. Docs: {doc_url}",
        "qa_message": "Iterator argument error in '{caller}'.",
        "qa_hint": "Review iterator arguments and validation. Docs: {doc_url}",
        "agent_message": "Iterator argument error in '{caller}'.",
        "agent_hint": "Review iterator arguments and validation. Docs: {doc_url}",
    },
    "MSM-ERR-DEP-001": {
        "title": "Missing library",
        "user_message": "Library '{library}' is not installed.",
        "user_hint": "Install '{library}' to use this functionality. Docs: {doc_url} | Issues: {issues_url}",
        "dev_message": "Missing library '{library}' required by '{caller}'.",
        "dev_hint": "Add dependency or guard optional path. Issues: {issues_url}",
        "qa_message": "Missing library '{library}' required by '{caller}'.",
        "qa_hint": "Add dependency or guard optional path. Issues: {issues_url}",
        "agent_message": "Missing library '{library}' required by '{caller}'.",
        "agent_hint": "Add dependency or guard optional path. Issues: {issues_url}",
    },
    "MSM-ERR-SYS-001": {
        "title": "Molecular system required",
        "user_message": "A molecular system is required for this operation.",
        "user_hint": "Provide a valid molecular system. Docs: {doc_url}",
        "dev_message": "Molecular system required in '{caller}'.",
        "dev_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "qa_message": "Molecular system required in '{caller}'.",
        "qa_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "agent_message": "Molecular system required in '{caller}'.",
        "agent_hint": "Validate inputs and update error handling. Docs: {doc_url}",
    },
    "MSM-ERR-SYS-002": {
        "title": "Multiple molecular systems required",
        "user_message": "Multiple molecular systems are required for this operation.",
        "user_hint": "Provide a list or set of molecular systems. Docs: {doc_url}",
        "dev_message": "Multiple molecular systems required in '{caller}'.",
        "dev_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "qa_message": "Multiple molecular systems required in '{caller}'.",
        "qa_hint": "Validate inputs and update error handling. Docs: {doc_url}",
        "agent_message": "Multiple molecular systems required in '{caller}'.",
        "agent_hint": "Validate inputs and update error handling. Docs: {doc_url}",
    },
    "MSM-ERR-CONV-001": {
        "title": "Incompatible conversion",
        "user_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "user_hint": "Check required attributes: {missing_arguments}. Docs: {doc_url}",
        "dev_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "dev_hint": "Ensure required attributes are provided: {missing_arguments}. Docs: {doc_url}",
        "qa_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "qa_hint": "Ensure required attributes are provided: {missing_arguments}. Docs: {doc_url}",
        "agent_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "agent_hint": "Ensure required attributes are provided: {missing_arguments}. Docs: {doc_url}",
    },
    "MSM-ERR-CONV-002": {
        "title": "Conversion not implemented",
        "user_message": "No conversion implemented from '{from_form}' to '{to_form}'.",
        "user_hint": "Check the documentation for available conversions. Docs: {doc_url}",
        "dev_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "dev_hint": "Implement conversion or document unsupported path. Docs: {doc_url}",
        "qa_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "qa_hint": "Implement conversion or document unsupported path. Docs: {doc_url}",
        "agent_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "agent_hint": "Implement conversion or document unsupported path. Docs: {doc_url}",
    },
    "MSM-ERR-ITER-002": {
        "title": "Iterator not implemented",
        "user_message": "Iterator not implemented for form '{form}'.",
        "user_hint": "Switch form or use another compatible function. Docs: {doc_url}",
        "dev_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "dev_hint": "Implement iterator or document unsupported form. Docs: {doc_url}",
        "qa_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "qa_hint": "Implement iterator or document unsupported form. Docs: {doc_url}",
        "agent_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "agent_hint": "Implement iterator or document unsupported form. Docs: {doc_url}",
    },
    "MSM-ERR-METHOD-001": {
        "title": "Method not implemented",
        "user_message": "This method is not implemented yet.",
        "user_hint": "Check alternative methods or wait for an update. Docs: {doc_url}",
        "dev_message": "Method not implemented in '{caller}'.",
        "dev_hint": "Implement method or document missing functionality. Docs: {doc_url}",
        "qa_message": "Method not implemented in '{caller}'.",
        "qa_hint": "Implement method or document missing functionality. Docs: {doc_url}",
        "agent_message": "Method not implemented in '{caller}'.",
        "agent_hint": "Implement method or document missing functionality. Docs: {doc_url}",
    },
    "MSM-ERR-FORM-001": {
        "title": "Form not supported",
        "user_message": "Form '{form}' is not supported by '{caller}'.",
        "user_hint": "Switch form or use another compatible function. Docs: {doc_url}",
        "dev_message": "Form '{form}' not supported in '{caller}'.",
        "dev_hint": "Implement support or document constraints. Docs: {doc_url}",
        "qa_message": "Form '{form}' not supported in '{caller}'.",
        "qa_hint": "Implement support or document constraints. Docs: {doc_url}",
        "agent_message": "Form '{form}' not supported in '{caller}'.",
        "agent_hint": "Implement support or document constraints. Docs: {doc_url}",
    },
    "MSM-ERR-SYNTAX-001": {
        "title": "Syntax not supported",
        "user_message": "Syntax '{syntax}' is not supported by '{caller}'.",
        "user_hint": "Check documentation for supported syntax. Docs: {doc_url}",
        "dev_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "dev_hint": "Implement support or document constraints. Docs: {doc_url}",
        "qa_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "qa_hint": "Implement support or document constraints. Docs: {doc_url}",
        "agent_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "agent_hint": "Implement support or document constraints. Docs: {doc_url}",
    },
    "MSM-ERR-FORM-002": {
        "title": "Form not allowed",
        "user_message": "The form used is not accepted by '{caller}'.",
        "user_hint": "Use a compatible form. Docs: {doc_url}",
        "dev_message": "Form not allowed in '{caller}'.",
        "dev_hint": "Implement support or document constraints. Docs: {doc_url}",
        "qa_message": "Form not allowed in '{caller}'.",
        "qa_hint": "Implement support or document constraints. Docs: {doc_url}",
        "agent_message": "Form not allowed in '{caller}'.",
        "agent_hint": "Implement support or document constraints. Docs: {doc_url}",
    },
    "MSM-ERR-IO-001": {
        "title": "File already handled",
        "user_message": "File '{filename}' is already handled by MolSysMT.",
        "user_hint": "Avoid registering the same file twice. Docs: {doc_url}",
        "dev_message": "File '{filename}' already handled.",
        "dev_hint": "Check file registry and duplicate handling. Docs: {doc_url}",
        "qa_message": "File '{filename}' already handled.",
        "qa_hint": "Check file registry and duplicate handling. Docs: {doc_url}",
        "agent_message": "File '{filename}' already handled.",
        "agent_hint": "Check file registry and duplicate handling. Docs: {doc_url}",
    },
}

SIGNALS = {
    "molsysmt.warning.selection": {"extra_required": ["caller"]},
    "molsysmt.warning.deprecation": {"extra_required": ["caller"]},
    "molsysmt.warning.cross_chain_bonds": {"extra_required": ["caller", "count", "pairs"]},
    "molsysmt.warning.download": {"extra_required": ["caller"]},
    "molsysmt.warning.not_digested": {"extra_required": ["argument"]},
    "molsysmt.warning.numba_jit": {"extra_required": ["kernel", "module"]},
    "molsysmt.warning.multi_container": {"extra_required": ["caller", "format"]},
    "molsysmt.warning.ambiguous_structure": {"extra_required": ["caller", "count"]},
    "molsysmt.error.argument": {"extra_required": ["argument", "value", "caller"]},
    "molsysmt.error.argument.choice": {"extra_required": ["argument", "value", "choices", "caller"]},
    "molsysmt.error.argument.length": {"extra_required": ["argument", "expected", "actual", "caller"]},
    "molsysmt.error.argument.conflict": {"extra_required": ["arg1", "arg2", "reason", "caller"]},
    "molsysmt.error.structure.inconsistency": {"extra_required": ["reason", "caller"]},
    "molsysmt.error.internal.algorithm": {"extra_required": ["reason", "caller"]},
    "molsysmt.error.iterator": {"extra_required": ["caller"]},
    "molsysmt.error.library_not_found": {"extra_required": ["library", "caller"]},
    "molsysmt.error.molecular_system_needed": {"extra_required": ["caller"]},
    "molsysmt.error.molecular_systems_needed": {"extra_required": ["caller"]},
    "molsysmt.error.not_compatible_conversion": {"extra_required": ["from_form", "to_form", "missing_arguments"]},
    "molsysmt.error.not_implemented_conversion": {"extra_required": ["from_form", "to_form", "caller"]},
    "molsysmt.error.not_implemented_iterator": {"extra_required": ["form", "caller"]},
    "molsysmt.error.not_implemented_method": {"extra_required": ["caller"]},
    "molsysmt.error.not_supported_form": {"extra_required": ["form", "caller"]},
    "molsysmt.error.not_supported_syntax": {"extra_required": ["syntax", "caller"]},
    "molsysmt.error.not_with_this_form": {"extra_required": ["caller"]},
    "molsysmt.error.file_already_handled": {"extra_required": ["filename"]},
}
