from __future__ import annotations

from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[2]

CATALOG = {
    "warnings": {
        "SelectionWarning": {
            "code": "MSM-WARN-SEL-001",
            "source": "molsysmt.warning.selection",
            "category": "selection",
            "level": "WARNING",
        },
        "MolSysMTDeprecationWarning": {
            "code": "MSM-WARN-DEP-001",
            "source": "molsysmt.warning.deprecation",
            "category": "deprecation",
            "level": "WARNING",
        },
        "CrossChainCovalentBondsWarning": {
            "code": "MSM-WARN-STRUCT-001",
            "source": "molsysmt.warning.cross_chain_bonds",
            "category": "structure",
            "level": "WARNING",
        },
        "DownloadWarning": {
            "code": "MSM-WARN-DL-001",
            "source": "molsysmt.warning.download",
            "category": "io",
            "level": "WARNING",
        },
        "NotDigestedArgumentWarning": {
            "code": "MSM-WARN-ARG-001",
            "source": "molsysmt.warning.not_digested",
            "category": "argument",
            "level": "WARNING",
        },
    },
    "exceptions": {
        "ArgumentError": {
            "code": "MSM-ERR-ARG-001",
            "source": "molsysmt.error.argument",
            "category": "argument",
            "level": "ERROR",
        },
        "IteratorError": {
            "code": "MSM-ERR-ITER-001",
            "source": "molsysmt.error.iterator",
            "category": "iterator",
            "level": "ERROR",
        },
        "LibraryNotFoundError": {
            "code": "MSM-ERR-DEP-001",
            "source": "molsysmt.error.library_not_found",
            "category": "dependency",
            "level": "ERROR",
        },
        "MolecularSystemNeededError": {
            "code": "MSM-ERR-SYS-001",
            "source": "molsysmt.error.molecular_system_needed",
            "category": "system",
            "level": "ERROR",
        },
        "MolecularSystemsNeededError": {
            "code": "MSM-ERR-SYS-002",
            "source": "molsysmt.error.molecular_systems_needed",
            "category": "system",
            "level": "ERROR",
        },
        "NotCompatibleConversionError": {
            "code": "MSM-ERR-CONV-001",
            "source": "molsysmt.error.not_compatible_conversion",
            "category": "conversion",
            "level": "ERROR",
        },
        "NotImplementedConversionError": {
            "code": "MSM-ERR-CONV-002",
            "source": "molsysmt.error.not_implemented_conversion",
            "category": "conversion",
            "level": "ERROR",
        },
        "NotImplementedIteratorError": {
            "code": "MSM-ERR-ITER-002",
            "source": "molsysmt.error.not_implemented_iterator",
            "category": "iterator",
            "level": "ERROR",
        },
        "NotImplementedMethodError": {
            "code": "MSM-ERR-METHOD-001",
            "source": "molsysmt.error.not_implemented_method",
            "category": "not_implemented",
            "level": "ERROR",
        },
        "NotSupportedFormError": {
            "code": "MSM-ERR-FORM-001",
            "source": "molsysmt.error.not_supported_form",
            "category": "not_supported",
            "level": "ERROR",
        },
        "NotSupportedSyntaxError": {
            "code": "MSM-ERR-SYNTAX-001",
            "source": "molsysmt.error.not_supported_syntax",
            "category": "not_supported",
            "level": "ERROR",
        },
        "NotWithThisFormError": {
            "code": "MSM-ERR-FORM-002",
            "source": "molsysmt.error.not_with_this_form",
            "category": "not_supported",
            "level": "ERROR",
        },
        "FileAlreadyHandledError": {
            "code": "MSM-ERR-IO-001",
            "source": "molsysmt.error.file_already_handled",
            "category": "io",
            "level": "ERROR",
        },
    },
}

CODES = {
    "MSM-WARN-SEL-001": {
        "title": "Selection warning",
        "user_message": "La seleccion indicada puede ser ambigua o incompleta.",
        "user_hint": "Revisa la cadena de seleccion y usa una expresion mas especifica.",
        "dev_message": "Selection warning in '{caller}'.",
        "dev_hint": "Review selection parsing and defaults.",
        "qa_message": "Selection warning in '{caller}'.",
        "qa_hint": "Review selection parsing and defaults.",
        "agent_message": "Selection warning in '{caller}'.",
        "agent_hint": "Review selection parsing and defaults.",
    },
    "MSM-WARN-DEP-001": {
        "title": "Deprecated API",
        "user_message": "Esta funcionalidad esta deprecada.",
        "user_hint": "Consulta la documentacion para el reemplazo recomendado.",
        "dev_message": "Deprecated API used in '{caller}'.",
        "dev_hint": "Update callsite to the recommended API.",
        "qa_message": "Deprecated API used in '{caller}'.",
        "qa_hint": "Update callsite to the recommended API.",
        "agent_message": "Deprecated API used in '{caller}'.",
        "agent_hint": "Update callsite to the recommended API.",
    },
    "MSM-WARN-STRUCT-001": {
        "title": "Cross-chain covalent bonds",
        "user_message": "Se detectaron enlaces covalentes entre cadenas.",
        "user_hint": "Verifica si estos enlaces son esperados en tu sistema.",
        "dev_message": "Cross-chain covalent bonds reported in '{caller}'.",
        "dev_hint": "Verify struct_conn interpretation and chain assignments.",
        "qa_message": "Cross-chain covalent bonds reported in '{caller}'.",
        "qa_hint": "Verify struct_conn interpretation and chain assignments.",
        "agent_message": "Cross-chain covalent bonds reported in '{caller}'.",
        "agent_hint": "Verify struct_conn interpretation and chain assignments.",
    },
    "MSM-WARN-DL-001": {
        "title": "Download warning",
        "user_message": "Se produjo una advertencia durante la descarga.",
        "user_hint": "Revisa la fuente o vuelve a intentar la descarga.",
        "dev_message": "Download warning in '{caller}'.",
        "dev_hint": "Check URL, connectivity, and retry policy.",
        "qa_message": "Download warning in '{caller}'.",
        "qa_hint": "Check URL, connectivity, and retry policy.",
        "agent_message": "Download warning in '{caller}'.",
        "agent_hint": "Check URL, connectivity, and retry policy.",
    },
    "MSM-WARN-ARG-001": {
        "title": "Argument not digested",
        "user_message": "El argumento '{argument}' no fue digerido.",
        "user_hint": "Revisa el argumento o consulta la documentacion de la funcion.",
        "dev_message": "Argument '{argument}' was not digested.",
        "dev_hint": "Check argdigest rules or mapping for '{argument}'.",
        "qa_message": "Argument '{argument}' was not digested.",
        "qa_hint": "Check argdigest rules or mapping for '{argument}'.",
        "agent_message": "Argument '{argument}' was not digested.",
        "agent_hint": "Check argdigest rules or mapping for '{argument}'.",
    },
    "MSM-ERR-ARG-001": {
        "title": "Argument error",
        "user_message": "Error en el argumento '{argument}' con valor '{value}'.",
        "user_hint": "Consulta la API para el formato esperado del argumento.",
        "dev_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "dev_hint": "Validate inputs and update docs if needed.",
        "qa_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "qa_hint": "Validate inputs and update docs if needed.",
        "agent_message": "Argument error in '{caller}' for '{argument}' with value '{value}'.",
        "agent_hint": "Validate inputs and update docs if needed.",
    },
    "MSM-ERR-ITER-001": {
        "title": "Iterator error",
        "user_message": "Se encontraron errores en los argumentos del iterador.",
        "user_hint": "Revisa los argumentos y el tipo de iterador usado.",
        "dev_message": "Iterator argument error in '{caller}'.",
        "dev_hint": "Review iterator arguments and validation.",
        "qa_message": "Iterator argument error in '{caller}'.",
        "qa_hint": "Review iterator arguments and validation.",
        "agent_message": "Iterator argument error in '{caller}'.",
        "agent_hint": "Review iterator arguments and validation.",
    },
    "MSM-ERR-DEP-001": {
        "title": "Missing library",
        "user_message": "La libreria '{library}' no esta instalada.",
        "user_hint": "Instala '{library}' para usar esta funcionalidad.",
        "dev_message": "Missing library '{library}' required by '{caller}'.",
        "dev_hint": "Add dependency or guard optional path.",
        "qa_message": "Missing library '{library}' required by '{caller}'.",
        "qa_hint": "Add dependency or guard optional path.",
        "agent_message": "Missing library '{library}' required by '{caller}'.",
        "agent_hint": "Add dependency or guard optional path.",
    },
    "MSM-ERR-SYS-001": {
        "title": "Molecular system required",
        "user_message": "Se requiere un sistema molecular para esta operacion.",
        "user_hint": "Proporciona un sistema molecular valido.",
        "dev_message": "Molecular system required in '{caller}'.",
        "dev_hint": "Validate inputs and update error handling.",
        "qa_message": "Molecular system required in '{caller}'.",
        "qa_hint": "Validate inputs and update error handling.",
        "agent_message": "Molecular system required in '{caller}'.",
        "agent_hint": "Validate inputs and update error handling.",
    },
    "MSM-ERR-SYS-002": {
        "title": "Multiple molecular systems required",
        "user_message": "Se requieren multiples sistemas moleculares para esta operacion.",
        "user_hint": "Proporciona una lista o conjunto de sistemas moleculares.",
        "dev_message": "Multiple molecular systems required in '{caller}'.",
        "dev_hint": "Validate inputs and update error handling.",
        "qa_message": "Multiple molecular systems required in '{caller}'.",
        "qa_hint": "Validate inputs and update error handling.",
        "agent_message": "Multiple molecular systems required in '{caller}'.",
        "agent_hint": "Validate inputs and update error handling.",
    },
    "MSM-ERR-CONV-001": {
        "title": "Incompatible conversion",
        "user_message": "Conversion no compatible de '{from_form}' a '{to_form}'.",
        "user_hint": "Revisa los atributos requeridos: {missing_arguments}.",
        "dev_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "dev_hint": "Ensure required attributes are provided: {missing_arguments}.",
        "qa_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "qa_hint": "Ensure required attributes are provided: {missing_arguments}.",
        "agent_message": "Incompatible conversion from '{from_form}' to '{to_form}'.",
        "agent_hint": "Ensure required attributes are provided: {missing_arguments}.",
    },
    "MSM-ERR-CONV-002": {
        "title": "Conversion not implemented",
        "user_message": "No hay conversion implementada de '{from_form}' a '{to_form}'.",
        "user_hint": "Consulta la documentacion para conversiones disponibles.",
        "dev_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "dev_hint": "Implement conversion or document unsupported path.",
        "qa_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "qa_hint": "Implement conversion or document unsupported path.",
        "agent_message": "Conversion not implemented from '{from_form}' to '{to_form}' in '{caller}'.",
        "agent_hint": "Implement conversion or document unsupported path.",
    },
    "MSM-ERR-ITER-002": {
        "title": "Iterator not implemented",
        "user_message": "El iterador no esta implementado para la forma '{form}'.",
        "user_hint": "Cambia la forma o usa otra funcion compatible.",
        "dev_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "dev_hint": "Implement iterator or document unsupported form.",
        "qa_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "qa_hint": "Implement iterator or document unsupported form.",
        "agent_message": "Iterator not implemented for form '{form}' in '{caller}'.",
        "agent_hint": "Implement iterator or document unsupported form.",
    },
    "MSM-ERR-METHOD-001": {
        "title": "Method not implemented",
        "user_message": "Este metodo no esta implementado aun.",
        "user_hint": "Consulta metodos alternativos o espera una actualizacion.",
        "dev_message": "Method not implemented in '{caller}'.",
        "dev_hint": "Implement method or document missing functionality.",
        "qa_message": "Method not implemented in '{caller}'.",
        "qa_hint": "Implement method or document missing functionality.",
        "agent_message": "Method not implemented in '{caller}'.",
        "agent_hint": "Implement method or document missing functionality.",
    },
    "MSM-ERR-FORM-001": {
        "title": "Form not supported",
        "user_message": "La forma '{form}' no es compatible con '{caller}'.",
        "user_hint": "Cambia la forma o usa otra funcion compatible.",
        "dev_message": "Form '{form}' not supported in '{caller}'.",
        "dev_hint": "Implement support or document constraints.",
        "qa_message": "Form '{form}' not supported in '{caller}'.",
        "qa_hint": "Implement support or document constraints.",
        "agent_message": "Form '{form}' not supported in '{caller}'.",
        "agent_hint": "Implement support or document constraints.",
    },
    "MSM-ERR-SYNTAX-001": {
        "title": "Syntax not supported",
        "user_message": "La sintaxis '{syntax}' no es compatible con '{caller}'.",
        "user_hint": "Revisa la documentacion de sintaxis soportada.",
        "dev_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "dev_hint": "Implement support or document constraints.",
        "qa_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "qa_hint": "Implement support or document constraints.",
        "agent_message": "Syntax '{syntax}' not supported in '{caller}'.",
        "agent_hint": "Implement support or document constraints.",
    },
    "MSM-ERR-FORM-002": {
        "title": "Form not allowed",
        "user_message": "La forma usada no es aceptada por '{caller}'.",
        "user_hint": "Usa una forma compatible.",
        "dev_message": "Form not allowed in '{caller}'.",
        "dev_hint": "Implement support or document constraints.",
        "qa_message": "Form not allowed in '{caller}'.",
        "qa_hint": "Implement support or document constraints.",
        "agent_message": "Form not allowed in '{caller}'.",
        "agent_hint": "Implement support or document constraints.",
    },
    "MSM-ERR-IO-001": {
        "title": "File already handled",
        "user_message": "El archivo '{filename}' ya esta siendo manejado por MolSysMT.",
        "user_hint": "Evita registrar el mismo archivo dos veces.",
        "dev_message": "File '{filename}' already handled.",
        "dev_hint": "Check file registry and duplicate handling.",
        "qa_message": "File '{filename}' already handled.",
        "qa_hint": "Check file registry and duplicate handling.",
        "agent_message": "File '{filename}' already handled.",
        "agent_hint": "Check file registry and duplicate handling.",
    },
}

SIGNALS = {
    "molsysmt.warning.selection": {"extra_required": ["caller"]},
    "molsysmt.warning.deprecation": {"extra_required": ["caller"]},
    "molsysmt.warning.cross_chain_bonds": {"extra_required": ["caller", "count", "pairs"]},
    "molsysmt.warning.download": {"extra_required": ["caller"]},
    "molsysmt.warning.not_digested": {"extra_required": ["argument"]},
    "molsysmt.error.argument": {"extra_required": ["argument", "value", "caller"]},
    "molsysmt.error.iterator": {"extra_required": ["caller"]},
    "molsysmt.error.library_not_found": {"extra_required": ["library", "caller"]},
    "molsysmt.error.molecular_system_needed": {"extra_required": ["caller"]},
    "molsysmt.error.molecular_systems_needed": {"extra_required": ["caller"]},
    "molsysmt.error.not_compatible_conversion": {"extra_required": ["from_form", "to_form", "missing_arguments"]},
    "molsysmt.error.not_implemented_conversion": {"extra_required": ["from_form", "to_form", "caller"]},
    "molsysmt.error.not_implemented_iterator": {"extra_required": ["form", "caller"]},
    "molsysmt.error.not_implemented_method": {"extra_required": ["caller"]},
    "molsysmt.error.not_supported_form": {"extra_required": ["form", "caller"]},
    "molsysmt.error.not_supported_syntax": {"extra_required": ["syntax", "caller"]},
    "molsysmt.error.not_with_this_form": {"extra_required": ["caller"]},
    "molsysmt.error.file_already_handled": {"extra_required": ["filename"]},
}
