channels:
- uibcdf
- conda-forge
- ambermd
dependencies:
- python
- pip
- h5py
- numpy
- numba
- argdigest
- depdigest
- smonitor
- pyunitwizard
- pandas
- molsysviewer
- networkx
- tqdm
- matplotlib
