from .attributes import attributes
from .attributes import topological_attributes as _topological_attributes
from .attributes import structural_attributes as _structural_attributes
from .attributes import mechanical_attributes as _mechanical_attributes
from .attributes import attribute_synonyms as _attribute_synonyms
from .attributes import independent_attributes as _independent_attributes

from .is_attribute import is_attribute
from .is_structural_attribute import is_structural_attribute
from .is_topological_attribute import is_topological_attribute
from .is_mechanical_attribute import is_mechanical_attribute

from .bonds_are_required_to_get_attribute import bonds_are_required_to_get_attribute

