"""Resource custody checks using a private inert LEaP executable."""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "tleap/check_tleap.sh"


@pytest.mark.skipif(os.name == "nt", reason="The developer helper is a Bash script.")
@pytest.mark.parametrize("child_exit", [0, 17])
@pytest.mark.parametrize("relative_binary", [False, True])
def test_check_isolates_child_outputs_and_retires_scratch(
    tmp_path, child_exit, relative_binary
):
    bash = shutil.which("bash")
    if bash is None:
        pytest.skip("Bash is unavailable.")
    caller = tmp_path / "caller"
    caller.mkdir()
    sentinel = caller / "leap.log"
    sentinel.write_text("caller-owned evidence", encoding="utf-8")
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    bin_dir = caller / "bin with spaces"
    bin_dir.mkdir()
    binary = bin_dir / "tleap"
    receipt = tmp_path / "receipt.json"
    binary.write_text(
        f"#!{sys.executable}\n"
        "import json, os, sys\n"
        "from pathlib import Path\n"
        "Path('leap.log').write_text('generated by private child')\n"
        "Path(os.environ['TEST_RECEIPT']).write_text(json.dumps({'cwd': str(Path.cwd()), 'input': Path(sys.argv[2]).read_text()}))\n"
        "print('private LEaP child')\n"
        f"sys.exit({child_exit})\n",
        encoding="utf-8",
    )
    binary.chmod(0o755)
    environment = os.environ.copy()
    environment.update(
        TLEAP_BIN=str(binary.relative_to(caller) if relative_binary else binary),
        TMPDIR=str(scratch),
        TEST_RECEIPT=str(receipt),
    )
    result = subprocess.run(
        [bash, str(SCRIPT)], cwd=caller, env=environment, text=True, capture_output=True
    )
    assert (result.returncode == 0) == (child_exit == 0), result.stdout + result.stderr
    observed = json.loads(receipt.read_text())
    assert Path(observed["cwd"]).parent == scratch
    assert observed["input"] == "quit\n"
    assert sentinel.read_text() == "caller-owned evidence"
    assert list(scratch.iterdir()) == []
    assert binary.exists()
    if child_exit:
        assert "private LEaP child" in result.stderr
