"""Declaring only explicit or deterministically derived SDF attributes."""

from molsysmt.attribute.attributes import attributes as _all_attributes

attributes = dict.fromkeys(_all_attributes, False)
for _attribute in (
    "atom_index",
    "atom_id",
    "atom_name",
    "atom_type",
    "isotope",
    "formal_charge",
    "atom_is_aromatic",
    "n_unpaired_electrons",
    "bond_index",
    "bond_id",
    "bond_type",
    "bond_order",
    "fractional_bond_order",
    "bond_is_aromatic",
    "bond_evidence",
    "bond_donor_atom_index",
    "bond_acceptor_atom_index",
    "bond_joins_components",
    "bonded_atoms",
    "bonded_atom_pairs",
    "inner_bond_index",
    "inner_bonded_atoms",
    "inner_bonded_atom_pairs",
    "component_index",
    "molecule_index",
    "molecule_id",
    "molecule_name",
    "molecule_type",
    "entity_index",
    "entity_id",
    "entity_name",
    "entity_type",
    "connectivity_completeness",
    "component_completeness",
    "component_evidence",
    "coordinates",
    "structure_index",
    "structure_id",
    "n_structures",
    "n_atoms",
    "n_bonds",
    "n_inner_bonds",
    "n_components",
    "n_molecules",
    "n_entities",
    "n_groups",
    "n_chains",
    "n_chemical_states",
    "chemical_state_index",
    "chemical_state_id",
    "reference_chemical_state_index",
    "n_amino_acids",
    "n_nucleotides",
    "n_ions",
    "n_waters",
    "n_small_molecules",
    "n_peptides",
    "n_proteins",
    "n_dnas",
    "n_rnas",
    "n_lipids",
    "n_polysaccharides",
    "n_saccharides",
):
    attributes[_attribute] = True
del _all_attributes, _attribute
