import numpy as np

name = [
    'ACE',
    'NME',
    '00C',
    '01W',
    '02K',
    '02L',
    '03Y',
    '07O',
    '08P',
    '0A0',
    '0A1',
    '0A2',
    '0A8',
    '0AA',
    '0AB',
    '0AC',
    '0AF',
    '0AG',
    '0AH',
    '0AK',
    '0BN',
    '0CS',
    '0E5',
    '0EA',
    '0FL',
    '0NC',
    '0WZ',
    '0Y8',
    '143',
    '193',
    '1OP',
    '1PA',
    '1PI',
    '1TQ',
    '1TY',
    '1X6',
    '200',
    '23F',
    '23S',
    '26B',
    '2AD',
    '2AG',
    '2AO',
    '2AS',
    '2CO',
    '2DO',
    '2FM',
    '2HF',
    '2KK',
    '2KP',
    '2LU',
    '2ML',
    '2MR',
    '2MT',
    '2OR',
    '2PI',
    '2QZ',
    '2R3',
    '2SI',
    '2TL',
    '2TY',
    '2VA',
    '2XA',
    '32S',
    '32T',
    '33X',
    '3AH',
    '3AR',
    '3CF',
    '3GA',
    '3MD',
    '3NF',
    '3QN',
    '3TY',
    '3XH',
    '4BF',
    '4CF',
    '4CY',
    '4DP',
    '4FB',
    '4FW',
    '4HT',
    '4IN',
    '4MM',
    '4PH',
    '4U7',
    '56A',
    '5AB',
    '5CS',
    '5CW',
    '5HP',
    '6CL',
    '6CW',
    '6GL',
    '6HN',
    '7JA',
    '9NE',
    '9NF',
    '9NR',
    '9NV',
    'A5N',
    'A66',
    'AA3',
    'AA4',
    'AAR',
    'AB7',
    'ABA',
    'ACB',
    'ACL',
    'ADD',
    'AEA',
    'AEI',
    'AFA',
    'AGM',
    'AGT',
    'AHB',
    'AHH',
    'AHO',
    'AHP',
    'AHS',
    'AHT',
    'AIB',
    'AKL',
    'AKZ',
    'ALA',
    'ALC',
    'ALM',
    'ALN',
    'ALO',
    'ALS',
    'ALT',
    'ALV',
    'ALY',
    'AN8',
    'APE',
    'APH',
    'API',
    'APK',
    'APM',
    'APP',
    'AR2',
    'AR4',
    'AR7',
    'ARG',
    'ARM',
    'ARO',
    'ARV',
    'AS2',
    'AS9',
    'ASA',
    'ASB',
    'ASH',
    'ASI',
    'ASK',
    'ASL',
    'ASM',
    'ASN',
    'ASP',
    'ASQ',
    'ASX',
    'AVN',
    'AYA',
    'AZK',
    'AZS',
    'AZY',
    'B1F',
    'B2A',
    'B2F',
    'B2I',
    'B2V',
    'B3A',
    'B3D',
    'B3E',
    'B3K',
    'B3L',
    'B3M',
    'B3Q',
    'B3S',
    'B3T',
    'B3U',
    'B3X',
    'B3Y',
    'BB6',
    'BB7',
    'BB8',
    'BB9',
    'BBC',
    'BCS',
    'BE2',
    'BFD',
    'BG1',
    'BH2',
    'BHD',
    'BIF',
    'BIL',
    'BIU',
    'BJH',
    'BL2',
    'BLE',
    'BLY',
    'BMT',
    'BNN',
    'BNO',
    'BOR',
    'BPE',
    'BSE',
    'BTA',
    'BTC',
    'BTR',
    'BUC',
    'BUG',
    'C1X',
    'C22',
    'C3Y',
    'C4R',
    'C5C',
    'C66',
    'C6C',
    'CAF',
    'CAL',
    'CAS',
    'CAV',
    'CAY',
    'CCL',
    'CCS',
    'CDE',
    'CDV',
    'CEA',
    'CGA',
    'CGU',
    'CHF',
    'CHG',
    'CHP',
    'CHS',
    'CIR',
    'CLE',
    'CLG',
    'CLH',
    'CME',
    'CMH',
    'CML',
    'CMT',
    'CPC',
    'CPI',
    'CR5',
    'CS0',
    'CS1',
    'CS3',
    'CS4',
    'CSA',
    'CSB',
    'CSD',
    'CSE',
    'CSJ',
    'CSO',
    'CSP',
    'CSR',
    'CSS',
    'CSU',
    'CSW',
    'CSX',
    'CSZ',
    'CTE',
    'CTH',
    'CUC',
    'CWR',
    'CXM',
    'CY0',
    'CY1',
    'CY3',
    'CY4',
    'CYA',
    'CYD',
    'CYF',
    'CYG',
    'CYJ',
    'CYM',
    'CYQ',
    'CYR',
    'CYS',
    'CZ2',
    'CZZ',
    'D11',
    'D3P',
    'D4P',
    'DA2',
    'DAB',
    'DAH',
    'DAL',
    'DAR',
    'DAS',
    'DBB',
    'DBS',
    'DBU',
    'DBY',
    'DBZ',
    'DC2',
    'DCL',
    'DCY',
    'DDE',
    'DFI',
    'DFO',
    'DGH',
    'DGL',
    'DGN',
    'DHA',
    'DHI',
    'DHL',
    'DHN',
    'DHP',
    'DHV',
    'DI7',
    'DIL',
    'DIR',
    'DIV',
    'DLE',
    'DLS',
    'DLY',
    'DM0',
    'DMH',
    'DMK',
    'DMT',
    'DNE',
    'DNL',
    'DNP',
    'DNS',
    'DOA',
    'DOH',
    'DON',
    'DPL',
    'DPN',
    'DPP',
    'DPQ',
    'DPR',
    'DSE',
    'DSG',
    'DSN',
    'DSP',
    'DTH',
    'DTR',
    'DTY',
    'DVA',
    'DYS',
    'ECC',
    'EFC',
    'EHP',
    'ESB',
    'ESC',
    'EXY',
    'EYS',
    'F2F',
    'FAK',
    'FB5',
    'FB6',
    'FCL',
    'FGA',
    'FGL',
    'FGP',
    'FH7',
    'FHL',
    'FHO',
    'FLA',
    'FLE',
    'FLT',
    'FME',
    'FOE',
    'FP9',
    'FRD',
    'FT6',
    'FTR',
    'FTY',
    'FVA',
    'FZN',
    'GAU',
    'GCM',
    'GFT',
    'GGL',
    'GHG',
    'GHP',
    'GL3',
    'GLH',
    'GLJ',
    'GLK',
    'GLM',
    'GLN',
    'GLQ',
    'GLU',
    'GLX',
    'GLY',
    'GLZ',
    'GMA',
    'GND',
    'GPL',
    'GSC',
    'GSU',
    'GT9',
    'GVL',
    'H14',
    'H5M',
    'HAC',
    'HAR',
    'HBN',
    'HCS',
    'HFA',
    'HGL',
    'HHI',
    'HIA',
    'HIC',
    'HIP',
    'HIQ',
    'HIS',
    'HL2',
    'HLU',
    'HMR',
    'HPC',
    'HPE',
    'HPH',
    'HPQ',
    'HQA',
    'HRG',
    'HRP',
    'HS8',
    'HS9',
    'HSE',
    'HSL',
    'HSO',
    'HTI',
    'HTN',
    'HTR',
    'HV5',
    'HVA',
    'HY3',
    'HYP',
    'HZP',
    'I2M',
    'I58',
    'IAM',
    'IAR',
    'IAS',
    'IEL',
    'IGL',
    'IIL',
    'ILE',
    'ILG',
    'ILX',
    'IML',
    'IOY',
    'IPG',
    'IT1',
    'IYR',
    'IYT',
    'IZO',
    'JJJ',
    'JJK',
    'JJL',
    'K1R',
    'KCX',
    'KGC',
    'KNB',
    'KOR',
    'KPI',
    'KST',
    'KYN',
    'KYQ',
    'L2A',
    'LA2',
    'LAA',
    'LAL',
    'LBY',
    'LCK',
    'LCX',
    'LCZ',
    'LDH',
    'LED',
    'LEF',
    'LEH',
    'LEI',
    'LEM',
    'LEN',
    'LET',
    'LEU',
    'LEX',
    'LHC',
    'LLP',
    'LLY',
    'LME',
    'LMF',
    'LMQ',
    'LP6',
    'LPD',
    'LPG',
    'LPL',
    'LPS',
    'LSO',
    'LTA',
    'LTR',
    'LVG',
    'LVN',
    'LYF',
    'LYK',
    'LYM',
    'LYN',
    'LYR',
    'LYS',
    'LYX',
    'LYZ',
    'M0H',
    'M2L',
    'M2S',
    'M30',
    'M3L',
    'MA',
    'MAA',
    'MAI',
    'MBQ',
    'MC1',
    'MCG',
    'MCL',
    'MCS',
    'MD3',
    'MD6',
    'MDF',
    'MDH',
    'MEA',
    'MED',
    'MEG',
    'MEN',
    'MEQ',
    'MET',
    'MEU',
    'MF3',
    'MGG',
    'MGN',
    'MGY',
    'MHL',
    'MHO',
    'MHS',
    'MIS',
    'MK8',
    'ML3',
    'MLE',
    'MLL',
    'MLY',
    'MLZ',
    'MME',
    'MMO',
    'MND',
    'MNL',
    'MNV',
    'MOD',
    'MP8',
    'MPH',
    'MPJ',
    'MPQ',
    'MSA',
    'MSE',
    'MSL',
    'MSO',
    'MSP',
    'MT2',
    'MTY',
    'MVA',
    'N10',
    'N2C',
    'N7P',
    'N80',
    'N8P',
    'NA8',
    'NAL',
    'NAM',
    'NB8',
    'NBQ',
    'NC1',
    'NCB',
    'NCY',
    'NDF',
    'NEM',
    'NEP',
    'NFA',
    'NHL',
    'NIY',
    'NLE',
    'NLN',
    'NLO',
    'NLP',
    'NLQ',
    'NMC',
    'NMM',
    'NNH',
    'NPH',
    'NPI',
    'NSK',
    'NTR',
    'NTY',
    'NVA',
    'NYS',
    'NZH',
    'O12',
    'OAR',
    'OAS',
    'OBF',
    'OBS',
    'OCS',
    'OCY',
    'OHI',
    'OHS',
    'OIC',
    'OLE',
    'OLT',
    'OLZ',
    'OMT',
    'ONH',
    'ONL',
    'OPR',
    'ORN',
    'ORQ',
    'OSE',
    'OTB',
    'OTH',
    'OXX',
    'P1L',
    'P2Y',
    'PAQ',
    'PAS',
    'PAT',
    'PAU',
    'PBB',
    'PBF',
    'PCA',
    'PCC',
    'PCE',
    'PCS',
    'PDL',
    'PEC',
    'PF5',
    'PFF',
    'PFX',
    'PG1',
    'PG9',
    'PGL',
    'PGY',
    'PH6',
    'PHA',
    'PHD',
    'PHE',
    'PHI',
    'PHL',
    'PHM',
    'PIV',
    'PLE',
    'PM3',
    'POM',
    'PPN',
    'PR3',
    'PR9',
    'PRO',
    'PRS',
    'PSA',
    'PSH',
    'PTA',
    'PTH',
    'PTM',
    'PTR',
    'PVH',
    'PVL',
    'PYA',
    'PYL',
    'PYX',
    'QCS',
    'QMM',
    'QPA',
    'QPH',
    'R1A',
    'R4K',
    'RE0',
    'RE3',
    'RON',
    'RVX',
    'RZ4',
    'S1H',
    'S2C',
    'S2D',
    'S2P',
    'SAC',
    'SAH',
    'SAR',
    'SBL',
    'SCH',
    'SCS',
    'SCY',
    'SD2',
    'SDP',
    'SE7',
    'SEB',
    'SEC',
    'SEG',
    'SEL',
    'SEM',
    'SEN',
    'SEP',
    'SER',
    'SET',
    'SGB',
    'SHC',
    'SHP',
    'SHR',
    'SIB',
    'SLR',
    'SLZ',
    'SMC',
    'SME',
    'SMF',
    'SNC',
    'SNN',
    'SOC',
    'SOY',
    'SRZ',
    'STY',
    'SUB',
    'SUN',
    'SVA',
    'SVV',
    'SVW',
    'SVX',
    'SVY',
    'SVZ',
    'SYS',
    'T11',
    'T66',
    'TA4',
    'TAV',
    'TBG',
    'TBM',
    'TCQ',
    'TCR',
    'TDD',
    'TFQ',
    'TH6',
    'THC',
    'THO',
    'THR',
    'THZ',
    'TIH',
    'TMB',
    'TMD',
    'TNB',
    'TNR',
    'TOQ',
    'TPH',
    'TPL',
    'TPO',
    'TPQ',
    'TQI',
    'TQQ',
    'TRF',
    'TRG',
    'TRN',
    'TRO',
    'TRP',
    'TRQ',
    'TRW',
    'TRX',
    'TRY',
    'TST',
    'TTQ',
    'TTS',
    'TXY',
    'TY1',
    'TY2',
    'TY3',
    'TY5',
    'TYB',
    'TYI',
    'TYJ',
    'TYN',
    'TYO',
    'TYQ',
    'TYR',
    'TYS',
    'TYT',
    'TYW',
    'TYX',
    'TYY',
    'TZB',
    'TZO',
    'UMA',
    'UN1',
    'UN2',
    'UNK',
    'VAD',
    'VAF',
    'VAL',
    'VB1',
    'VDL',
    'VLL',
    'VLM',
    'VMS',
    'VOL',
    'WLU',
    'WPA',
    'WRP',
    'WVL',
    'X2W',
    'XCN',
    'XCP',
    'XDT',
    'XPL',
    'XPR',
    'XSN',
    'XX1',
    'YCM',
    'YOF',
    'YTH',
    'Z01',
    'ZAL',
    'ZCL',
    'ZFB',
    'ZU0',
    'ZZJ'
 ]

# This comes from MDTRAJ, we have to check if there is a place where this can also be found.
aa3_to_aa1 =  {'ACE': None, 'NME':  None, '00C': 'C', '01W':  'X', '02K':
'A', '02L':  'N', '03Y': 'C',  '07O': 'C', '08P':  'C', '0A0': 'D',  '0A1': 'Y',
'0A2': 'K', '0A8':  'C', '0AA': 'V', '0AB': 'V', '0AC':  'G', '0AF': 'W', '0AG':
'L', '0AH':  'S', '0AK': 'D',  '0BN': 'F', '0CS':  'A', '0E5': 'T',  '0EA': 'Y',
'0FL': 'A', '0NC':  'A', '0WZ': 'Y', '0Y8': 'P', '143':  'C', '193': 'X', '1OP':
'Y', '1PA':  'F', '1PI': 'A',  '1TQ': 'W', '1TY':  'Y', '1X6': 'S',  '200': 'F',
'23F': 'F', '23S':  'X', '26B': 'T', '2AD': 'X', '2AG':  'A', '2AO': 'X', '2AS':
'X', '2CO':  'C', '2DO': 'X',  '2FM': 'M', '2HF':  'H', '2KK': 'K',  '2KP': 'K',
'2LU': 'L', '2ML':  'L', '2MR': 'R', '2MT': 'P', '2OR':  'R', '2PI': 'X', '2QZ':
'T', '2R3':  'Y', '2SI': 'X',  '2TL': 'T', '2TY':  'Y', '2VA': 'V',  '2XA': 'C',
'32S': 'X', '32T':  'X', '33X': 'A', '3AH': 'H', '3AR':  'X', '3CF': 'F', '3GA':
'A', '3MD':  'D', '3NF': 'Y',  '3QN': 'K', '3TY':  'X', '3XH': 'G',  '4BF': 'Y',
'4CF': 'F', '4CY':  'M', '4DP': 'W', '4FB': 'P', '4FW':  'W', '4HT': 'W', '4IN':
'W', '4MM':  'X', '4PH': 'F',  '4U7': 'A', '56A':  'H', '5AB': 'A',  '5CS': 'C',
'5CW': 'W', '5HP':  'E', '6CL': 'K', '6CW': 'W', '6GL':  'A', '6HN': 'K', '7JA':
'I', '9NE':  'E', '9NF': 'F',  '9NR': 'R', '9NV':  'V', 'A5N': 'N',  'A66': 'X',
'AA3': 'A', 'AA4':  'A', 'AAR': 'R', 'AB7': 'X', 'ABA':  'A', 'ACB': 'D', 'ACL':
'R', 'ADD':  'X', 'AEA': 'X',  'AEI': 'D', 'AFA':  'N', 'AGM': 'R',  'AGT': 'C',
'AHB': 'N', 'AHH':  'X', 'AHO': 'A', 'AHP': 'A', 'AHS':  'X', 'AHT': 'X', 'AIB':
'A', 'AKL':  'D', 'AKZ': 'D',  'ALA': 'A', 'ALC':  'A', 'ALM': 'A',  'ALN': 'A',
'ALO': 'T', 'ALS':  'A', 'ALT': 'A', 'ALV': 'A', 'ALY':  'K', 'AN8': 'A', 'APE':
'X', 'APH':  'A', 'API': 'K',  'APK': 'K', 'APM':  'X', 'APP': 'X',  'AR2': 'R',
'AR4': 'E', 'AR7':  'R', 'ARG': 'R', 'ARM': 'R', 'ARO':  'R', 'ARV': 'X', 'AS2':
'D', 'AS9':  'X', 'ASA': 'D',  'ASB': 'D','ASH':  'D', 'ASI':  'D', 'ASK': 'D',  'ASL': 'D',
'ASM': 'X', 'ASN':  'N', 'ASP': 'D', 'ASQ': 'D', 'ASX':  'B', 'AVN': 'X', 'AYA':
'A', 'AZK':  'K', 'AZS': 'S',  'AZY': 'Y', 'B1F':  'F', 'B2A': 'A',  'B2F': 'F',
'B2I': 'I', 'B2V':  'V', 'B3A': 'A', 'B3D': 'D', 'B3E':  'E', 'B3K': 'K', 'B3L':
'X', 'B3M':  'X', 'B3Q': 'X',  'B3S': 'S', 'B3T':  'X', 'B3U': 'H',  'B3X': 'N',
'B3Y': 'Y', 'BB6':  'C', 'BB7': 'C', 'BB8': 'F', 'BB9':  'C', 'BBC': 'C', 'BCS':
'C', 'BE2':  'X', 'BFD': 'D',  'BG1': 'S', 'BH2':  'D', 'BHD': 'D',  'BIF': 'F',
'BIL': 'X', 'BIU':  'I', 'BJH': 'X', 'BL2': 'L', 'BLE':  'L', 'BLY': 'K', 'BMT':
'T', 'BNN':  'F', 'BNO': 'X',  'BOR': 'R', 'BPE':  'C', 'BSE': 'S',  'BTA': 'L',
'BTC': 'C', 'BTR':  'W', 'BUC': 'C', 'BUG': 'V', 'C1X':  'K', 'C22': 'A', 'C3Y':
'C', 'C4R':  'C', 'C5C': 'C',  'C66': 'X', 'C6C':  'C', 'CAF': 'C',  'CAL': 'X',
'CAS': 'C', 'CAV':  'X', 'CAY': 'C', 'CCL': 'K', 'CCS':  'C', 'CDE': 'X', 'CDV':
'X', 'CEA':  'C', 'CGA': 'E',  'CGU': 'E', 'CHF':  'X', 'CHG': 'X',  'CHP': 'G',
'CHS': 'X', 'CIR':  'R', 'CLE': 'L', 'CLG': 'K', 'CLH':  'K', 'CME': 'C', 'CMH':
'C', 'CML':  'C', 'CMT': 'C',  'CPC': 'X', 'CPI':  'X', 'CR5': 'G',  'CS0': 'C',
'CS1': 'C', 'CS3':  'C', 'CS4': 'C', 'CSA': 'C', 'CSB':  'C', 'CSD': 'C', 'CSE':
'C', 'CSJ':  'C', 'CSO': 'C',  'CSP': 'C', 'CSR':  'C', 'CSS': 'C',  'CSU': 'C',
'CSW': 'C', 'CSX':  'C', 'CSZ': 'C', 'CTE': 'W', 'CTH':  'T', 'CUC': 'X', 'CWR':
'S', 'CXM':  'M', 'CY0': 'C',  'CY1': 'C', 'CY3':  'C', 'CY4': 'C',  'CYA': 'C',
'CYD': 'C', 'CYF':  'C', 'CYG': 'C', 'CYJ': 'K', 'CYM':  'C', 'CYQ': 'C', 'CYR':
'C', 'CYS':  'C', 'CZ2': 'C',  'CZZ': 'C', 'D11':  'T', 'D3P': 'G',  'D4P': 'X',
'DA2': 'X', 'DAB':  'A', 'DAH': 'F', 'DAL': 'A', 'DAR':  'R', 'DAS': 'D', 'DBB':
'T', 'DBS':  'S', 'DBU': 'T',  'DBY': 'Y', 'DBZ':  'A', 'DC2': 'C',  'DCL': 'X',
'DCY': 'C', 'DDE':  'H', 'DFI': 'X', 'DFO': 'X', 'DGH':  'G', 'DGL': 'E', 'DGN':
'Q', 'DHA':  'S', 'DHI': 'H',  'DHL': 'X', 'DHN':  'V', 'DHP': 'X',  'DHV': 'V',
'DI7': 'Y', 'DIL':  'I', 'DIR': 'R', 'DIV': 'V', 'DLE':  'L', 'DLS': 'K', 'DLY':
'K', 'DM0':  'K', 'DMH': 'N',  'DMK': 'D', 'DMT':  'X', 'DNE': 'L',  'DNL': 'K',
'DNP': 'A', 'DNS':  'K', 'DOA': 'X', 'DOH': 'D', 'DON':  'L', 'DPL': 'P', 'DPN':
'F', 'DPP':  'A', 'DPQ': 'Y',  'DPR': 'P', 'DSE':  'S', 'DSG': 'N',  'DSN': 'S',
'DSP': 'D', 'DTH':  'T', 'DTR': 'W', 'DTY': 'Y', 'DVA':  'V', 'DYS': 'C', 'ECC':
'Q', 'EFC':  'C', 'EHP': 'F',  'ESB': 'Y', 'ESC':  'M', 'EXY': 'L',  'EYS': 'X',
'F2F': 'F', 'FAK':  'K', 'FB5': 'A', 'FB6': 'A', 'FCL':  'F', 'FGA': 'E', 'FGL':
'G', 'FGP':  'S', 'FH7': 'K',  'FHL': 'K', 'FHO':  'K', 'FLA': 'A',  'FLE': 'L',
'FLT': 'Y', 'FME':  'M', 'FOE': 'C', 'FP9': 'P', 'FRD':  'X', 'FT6': 'W', 'FTR':
'W', 'FTY':  'Y', 'FVA': 'V',  'FZN': 'K', 'GAU':  'E', 'GCM': 'X',  'GFT': 'S',
'GGL': 'E', 'GHG':  'Q', 'GHP': 'G', 'GL3': 'G', 'GLH':  'Q', 'GLJ': 'E', 'GLK':
'E', 'GLM':  'X', 'GLN': 'Q',  'GLQ': 'E', 'GLU':  'E', 'GLX': 'Z',  'GLY': 'G',
'GLZ': 'G', 'GMA':  'E', 'GND': 'X', 'GPL': 'K', 'GSC':  'G', 'GSU': 'E', 'GT9':
'C', 'GVL':  'S', 'H14': 'F',  'H5M': 'P', 'HAC':  'A', 'HAR': 'R',  'HBN': 'H',
'HCS': 'X', 'HFA':  'X', 'HGL': 'X', 'HHI': 'H', 'HIA':  'H', 'HIC': 'H', 'HIP':
'H', 'HIQ':  'H', 'HIS': 'H',  'HL2': 'L', 'HLU':  'L', 'HMR': 'R',  'HPC': 'F',
'HPE': 'F', 'HPH':  'F', 'HPQ': 'F', 'HQA': 'A', 'HRG':  'R', 'HRP': 'W', 'HS8':
'H', 'HS9':  'H', 'HSE': 'S',  'HSL': 'S', 'HSO':  'H', 'HTI': 'C',  'HTN': 'N',
'HTR': 'W', 'HV5':  'A', 'HVA': 'V', 'HY3': 'P', 'HYP':  'P', 'HZP': 'P', 'I2M':
'I', 'I58':  'K', 'IAM': 'A',  'IAR': 'R', 'IAS':  'D', 'IEL': 'K',  'IGL': 'G',
'IIL': 'I', 'ILE':  'I', 'ILG': 'E', 'ILX': 'I', 'IML':  'I', 'IOY': 'F', 'IPG':
'G', 'IT1':  'K', 'IYR': 'Y',  'IYT': 'T', 'IZO':  'M', 'JJJ': 'C',  'JJK': 'C',
'JJL': 'C', 'K1R':  'C', 'KCX': 'K', 'KGC': 'K', 'KNB':  'A', 'KOR': 'M', 'KPI':
'K', 'KST':  'K', 'KYN': 'W',  'KYQ': 'K', 'L2A':  'X', 'LA2': 'K',  'LAA': 'D',
'LAL': 'A', 'LBY':  'K', 'LCK': 'K', 'LCX': 'K', 'LCZ':  'X', 'LDH': 'K', 'LED':
'L', 'LEF':  'L', 'LEH': 'L',  'LEI': 'V', 'LEM':  'L', 'LEN': 'L',  'LET': 'K',
'LEU': 'L', 'LEX':  'L', 'LHC': 'X', 'LLP': 'K', 'LLY':  'K', 'LME': 'E', 'LMF':
'K', 'LMQ':  'Q', 'LP6': 'K',  'LPD': 'P', 'LPG':  'G', 'LPL': 'X',  'LPS': 'S',
'LSO': 'K', 'LTA':  'X', 'LTR': 'W', 'LVG': 'G', 'LVN':  'V', 'LYF': 'K', 'LYK':
'K', 'LYM':  'K', 'LYN': 'K',  'LYR': 'K', 'LYS':  'K', 'LYX': 'K',  'LYZ': 'K',
'M0H': 'C',  'M2L': 'K', 'M2S': 'M',  'M30': 'G', 'M3L': 'K',  'MA': 'A', 'MAA':
'A', 'MAI':  'R', 'MBQ': 'Y',  'MC1': 'S', 'MCG':  'X', 'MCL': 'K',  'MCS': 'C',
'MD3': 'C', 'MD6':  'G', 'MDF': 'Y', 'MDH': 'X', 'MEA':  'F', 'MED': 'M', 'MEG':
'E', 'MEN':  'N', 'MEQ': 'Q',  'MET': 'M', 'MEU':  'G', 'MF3': 'X',  'MGG': 'R',
'MGN': 'Q', 'MGY':  'G', 'MHL': 'L', 'MHO': 'M', 'MHS':  'H', 'MIS': 'S', 'MK8':
'L', 'ML3':  'K', 'MLE': 'L',  'MLL': 'L', 'MLY':  'K', 'MLZ': 'K',  'MME': 'M',
'MMO': 'R', 'MND':  'N', 'MNL': 'L', 'MNV': 'V', 'MOD':  'X', 'MP8': 'P', 'MPH':
'X', 'MPJ':  'X', 'MPQ': 'G',  'MSA': 'G', 'MSE':  'M', 'MSL': 'M',  'MSO': 'M',
'MSP': 'X', 'MT2':  'M', 'MTY': 'Y', 'MVA': 'V', 'N10':  'S', 'N2C': 'X', 'N7P':
'P', 'N80':  'P', 'N8P': 'P',  'NA8': 'A', 'NAL':  'A', 'NAM': 'A',  'NB8': 'N',
'NBQ': 'Y', 'NC1':  'S', 'NCB': 'A', 'NCY': 'X', 'NDF':  'F', 'NEM': 'H', 'NEP':
'H', 'NFA':  'F', 'NHL': 'E',  'NIY': 'Y', 'NLE':  'L', 'NLN': 'L',  'NLO': 'L',
'NLP': 'L', 'NLQ':  'Q', 'NMC': 'G', 'NMM': 'R', 'NNH':  'R', 'NPH': 'C', 'NPI':
'A', 'NSK':  'X', 'NTR': 'Y',  'NTY': 'Y', 'NVA':  'V', 'NYS': 'C',  'NZH': 'H',
'O12': 'X', 'OAR':  'R', 'OAS': 'S', 'OBF': 'X', 'OBS':  'K', 'OCS': 'C', 'OCY':
'C', 'OHI':  'H', 'OHS': 'D',  'OIC': 'X', 'OLE':  'X', 'OLT': 'T',  'OLZ': 'S',
'OMT': 'M', 'ONH':  'A', 'ONL': 'X', 'OPR': 'R', 'ORN':  'A', 'ORQ': 'R', 'OSE':
'S', 'OTB':  'X', 'OTH': 'T',  'OXX': 'D', 'P1L':  'C', 'P2Y': 'P',  'PAQ': 'Y',
'PAS': 'D', 'PAT':  'W', 'PAU': 'A', 'PBB': 'C', 'PBF':  'F', 'PCA': 'E', 'PCC':
'P', 'PCE':  'X', 'PCS': 'F',  'PDL': 'X', 'PEC':  'C', 'PF5': 'F',  'PFF': 'F',
'PFX': 'X', 'PG1':  'S', 'PG9': 'G', 'PGL': 'X', 'PGY':  'G', 'PH6': 'P', 'PHA':
'F', 'PHD':  'D', 'PHE': 'F',  'PHI': 'F', 'PHL':  'F', 'PHM': 'F',  'PIV': 'X',
'PLE': 'L', 'PM3':  'F', 'POM': 'P', 'PPN': 'F', 'PR3':  'C', 'PR9': 'P', 'PRO':
'P', 'PRS':  'P', 'PSA': 'F',  'PSH': 'H', 'PTA':  'X', 'PTH': 'Y',  'PTM': 'Y',
'PTR': 'Y', 'PVH':  'H', 'PVL': 'X', 'PYA': 'A', 'PYL':  'O', 'PYX': 'C', 'QCS':
'C', 'QMM':  'Q', 'QPA': 'C',  'QPH': 'F', 'R1A':  'C', 'R4K': 'W',  'RE0': 'W',
'RE3': 'W', 'RON':  'X', 'RVX': 'S', 'RZ4': 'S', 'S1H':  'S', 'S2C': 'C', 'S2D':
'A', 'S2P':  'A', 'SAC': 'S',  'SAH': 'C', 'SAR':  'G', 'SBL': 'S',  'SCH': 'C',
'SCS': 'C', 'SCY':  'C', 'SD2': 'X', 'SDP': 'S', 'SE7':  'A', 'SEB': 'S', 'SEC':
'U', 'SEG':  'A', 'SEL': 'S',  'SEM': 'S', 'SEN':  'S', 'SEP': 'S',  'SER': 'S',
'SET': 'S', 'SGB':  'S', 'SHC': 'C', 'SHP': 'G', 'SHR':  'K', 'SIB': 'C', 'SLR':
'P', 'SLZ':  'K', 'SMC': 'C',  'SME': 'M', 'SMF':  'F', 'SNC': 'C',  'SNN': 'N',
'SOC': 'C', 'SOY':  'S', 'SRZ': 'S', 'STY': 'Y', 'SUB':  'X', 'SUN': 'S', 'SVA':
'S', 'SVV':  'S', 'SVW': 'S',  'SVX': 'S', 'SVY':  'S', 'SVZ': 'S',  'SYS': 'C',
'T11': 'F', 'T66':  'X', 'TA4': 'X', 'TAV': 'D', 'TBG':  'V', 'TBM': 'T', 'TCQ':
'Y', 'TCR':  'W', 'TDD': 'L',  'TFQ': 'F', 'TH6':  'T', 'THC': 'T',  'THO': 'X',
'THR': 'T', 'THZ':  'R', 'TIH': 'A', 'TMB': 'T', 'TMD':  'T', 'TNB': 'C', 'TNR':
'S', 'TOQ':  'W', 'TPH': 'X',  'TPL': 'W', 'TPO':  'T', 'TPQ': 'Y',  'TQI': 'W',
'TQQ': 'W', 'TRF':  'W', 'TRG': 'K', 'TRN': 'W', 'TRO':  'W', 'TRP': 'W', 'TRQ':
'W', 'TRW':  'W', 'TRX': 'W',  'TRY': 'W', 'TST':  'X', 'TTQ': 'W',  'TTS': 'Y',
'TXY': 'Y', 'TY1':  'Y', 'TY2': 'Y', 'TY3': 'Y', 'TY5':  'Y', 'TYB': 'Y', 'TYI':
'Y', 'TYJ':  'Y', 'TYN': 'Y',  'TYO': 'Y', 'TYQ':  'Y', 'TYR': 'Y',  'TYS': 'Y',
'TYT': 'Y', 'TYW':  'Y', 'TYX': 'X', 'TYY': 'Y', 'TZB':  'X', 'TZO': 'X', 'UMA':
'A', 'UN1':  'X', 'UN2': 'X',  'UNK': 'X', 'VAD':  'V', 'VAF': 'V',  'VAL': 'V',
'VB1': 'K', 'VDL':  'X', 'VLL': 'X', 'VLM': 'X', 'VMS':  'X', 'VOL': 'X', 'WLU':
'L', 'WPA':  'F', 'WRP': 'W',  'WVL': 'V', 'X2W':  'E', 'XCN': 'C',  'XCP': 'X',
'XDT': 'T', 'XPL':  'O', 'XPR': 'P', 'XSN': 'N', 'XX1':  'K', 'YCM': 'C', 'YOF':
'Y', 'YTH':  'T', 'Z01': 'A',  'ZAL': 'A', 'ZCL':  'F', 'ZFB': 'X',  'ZU0': 'T',
'ZZJ': 'A'}

aa1s = set(list(aa3_to_aa1.values()))

