from molsysmt._private_tools.exceptions import BadCallError

where_get_argument = {

    'atom_index' : ['topology_item'],
    'atom_name' : ['topology_item'],
    'atom_id' : ['topology_item'],
    'atom_type' : ['topology_item'],
    'group_index' : ['topology_item'],
    'group_name' : ['topology_item'],
    'group_id' : ['topology_item'],
    'group_type' : ['topology_item'],
    'component_index' : ['topology_item'],
    'component_name' : ['topology_item'],
    'component_id' : ['topology_item'],
    'component_type' : ['topology_item'],
    'chain_index' : ['topology_item'],
    'chain_name' : ['topology_item'],
    'chain_id' : ['topology_item'],
    'chain_type' : ['topology_item'],
    'molecule_index' : ['topology_item'],
    'molecule_name' : ['topology_item'],
    'molecule_id' : ['topology_item'],
    'molecule_type' : ['topology_item'],
    'entity_index' : ['topology_item'],
    'entity_name' : ['topology_item'],
    'entity_id' : ['topology_item'],
    'entity_type' : ['topology_item'],

    'n_atoms' : ['topology_item', 'trajectory_item', 'coordinates_item'],
    'n_groups' : ['topology_item'],
    'n_components' : ['topology_item'],
    'n_chains' : ['topology_item'],
    'n_molecules' : ['topology_item'],
    'n_entities' : ['topology_item'],

    'bond_index' : ['bonds_item'],
    'bond_name' : ['bonds_item'],
    'bond_id' : ['bonds_item'],
    'bond_type' : ['bonds_item'],
    'bonded_atoms' : ['bonds_item'],
    'inner_bonded_atoms' : ['bonds_item'],
    'inner_bond_index' : ['bonds_item'],
    'n_bonds' : ['bonds_item'],
    'n_inner_bonds' : ['bonds_item'],

    'n_aminoacids' : ['topology_item'],
    'n_nucleotides' : ['topology_item'],
    'n_ions' : ['topology_item'],
    'n_waters' : ['topology_item'],
    'n_cosolutes' : ['topology_item'],
    'n_small_molecules' : ['topology_item'],
    'n_peptides' : ['topology_item'],
    'n_proteins' : ['topology_item'],
    'n_dnas' : ['topology_item'],
    'n_rnas' : ['topology_item'],

    'step' : ['trajectory_item'],
    'time' : ['trajectory_item'],
    'frame' : ['trajectory_item'],
    'n_frames' : ['trajectory_item', 'coordinates_item', 'box_item'],
    'coordinates' : ['trajectory_item', 'coordinates_item'],

    'box' : ['trajectory_item', 'box_item'],
    'box_shape' : ['trajectory_item', 'box_item'],
    'box_angles' : ['trajectory_item', 'box_item'],
    'box_lengths' : ['trajectory_item', 'box_item'],
    'box_volume' : ['trajectory_item', 'box_item'],

}


get_argument_synonym = {
    'atom_indices': 'atom_index',
    'atom_names': 'atom_name',
    'atom_ids': 'atom_id',
    'atom_types': 'atom_type',
    'group_indices': 'group_index',
    'group_names': 'group_name',
    'group_ids': 'group_id',
    'group_types': 'group_type',
    'component_indices': 'component_index',
    'component_names': 'component_name',
    'component_ids': 'component_id',
    'component_types': 'component_type',
    'chain_indices': 'chain_index',
    'chain_names': 'chain_name',
    'chain_ids': 'chain_id',
    'chain_types': 'chain_type',
    'molecule_indices': 'molecule_index',
    'molecule_names': 'molecule_name',
    'molecule_ids': 'molecule_id',
    'molecule_types': 'molecule_type',
    'entity_indices': 'entity_index',
    'entity_names': 'entity_name',
    'entity_ids': 'entity_id',
    'entity_types': 'entity_type',
    'bond_indices': 'bond_index',
    'bond_ids': 'bond_id',
    'bond_types': 'bond_type',
    'bonded_atom': 'bonded_atoms',
    'inner_bonded_atom': 'inner_bonded_atoms',
    'inner_bond_indices': 'inner_bond_index',
    'n_atom': 'n_atoms',
    'n_group': 'n_groups',
    'n_component': 'n_components',
    'n_chain': 'n_chains',
    'n_molecule': 'n_molecules',
    'n_entity': 'n_entities',
    'n_bond': 'n_bonds',
    'n_inner_bond': 'n_inner_bonds',
    'n_aminoacid': 'n_aminoacids',
    'n_nucleotide': 'n_nucleotides',
    'n_ion': 'n_ions',
    'n_water': 'n_waters',
    'n_cosolute': 'n_cosolutes',
    'n_small_molecule': 'n_small_molecules',
    'n_peptide': 'n_peptides',
    'n_protein': 'n_proteins',
    'n_dna': 'n_dnas',
    'n_rna': 'n_rnas',
    'residue_indices': 'group_index',
    'residue_index': 'group_index',
    'residue_names': 'group_name',
    'residue_name': 'group_name',
    'residue_ids': 'group_id',
    'residue_id': 'group_id',
    'residue_types': 'group_type',
    'residue_type': 'group_type',
    'n_residues': 'n_groups',
    'n_residue': 'n_groups',
    'steps': 'step',
    'times': 'time',
    'frames': 'frame',
    'n_frame': 'n_frames',
}


get_arguments = list(where_get_argument.keys())

def digest_get_argument(get_argument):

    tmp_get_argument = get_argument.lower()
    if tmp_get_argument in get_argument_synonym:
        tmp_get_argument = get_argument_synonymn[tmp_get_argument]
    if tmp_get_argument in get_arguments:
        return tmp_get_argument
    else:
        raise BadCallError()

