from .is_biopython_SeqRecord import is_biopython_SeqRecord
from molsysmt._private.exceptions import WrongFormError, WrongIndicesError, WrongStructureIndicesError
from molsysmt._private.exceptions import NotImplementedMethodError
from molsysmt._private.indices import digest_indices
from molsysmt._private.structure_indices import digest_structure_indices


