setup:
  channels: &setup_channels
    - defaults
  dependencies: &setup_dependencies
    - python
    - setuptools
    - numpy

production:
  channels: &production_channels
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - *setup_channels
  dependencies: &production_dependencies
    - python
    - numpy
    - pyunitwizard
    - sabueso
    - mmtf-python
    - pandas
    - mdtraj
    - mdanalysis
    - openmm
    - pdbfixer
    - openmmtools
    - biopython
    - nglview
    - parmed
    - pytraj
    - openopenmmreporters
    - openmolecularsystems

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies
    - pytest
    - pip
    - pytest-cov
    - codecov

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables

development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - *docs_dependencies
    - jupyterlab

conda-build:
  channels:
    - *production_channels
  dependencies:
    - anaconda-client
    - conda-build

