# DepDigest configuration for MolSysMT
from molsysmt._private.smonitor import LibraryNotFoundError

LIBRARIES = {
    'numpy': {'type': 'hard', 'pypi': 'numpy'},
    'pandas': {'type': 'hard', 'pypi': 'pandas'},
    'mdtraj': {'type': 'soft', 'pypi': 'mdtraj'},
    'openmm': {'type': 'soft', 'pypi': 'openmm'},
    'openmmtools': {'type': 'soft', 'pypi': 'openmmtools'},
    'MDAnalysis': {'type': 'soft', 'pypi': 'MDAnalysis'},
    'parmed': {'type': 'soft', 'pypi': 'parmed'},
    'pytraj': {'type': 'soft', 'pypi': 'pytraj'},
    'nglview': {'type': 'soft', 'pypi': 'nglview'},
    'molsysviewer': {'type': 'hard', 'pypi': 'molsysviewer'},
    'pdbfixer': {'type': 'soft', 'pypi': 'pdbfixer'},
    'Bio': {'type': 'soft', 'pypi': 'biopython'},
    'rdkit': {'type': 'soft', 'pypi': 'rdkit'},
    'openff.toolkit': {'type': 'soft', 'pypi': 'openff-toolkit'},
    'plotly': {'type': 'soft', 'pypi': 'plotly'},
    'mmtf': {'type': 'soft', 'pypi': 'mmtf-python'},
    'yaml': {'type': 'soft', 'pypi': 'PyYAML'},
    'taichi': {'type': 'soft', 'pypi': 'taichi'},
}

MAPPING = {
    'mdtraj_Trajectory': 'mdtraj',
    'mdtraj_Topology': 'mdtraj',
    'mdtraj_DCDTrajectoryFile': 'mdtraj',
    'mdtraj_HDF5TrajectoryFile': 'mdtraj',
    'mdtraj_XTCTrajectoryFile': 'mdtraj',
    'mdtraj_GroTrajectoryFile': 'mdtraj',
    'mdtraj_AmberRestartFile': 'mdtraj',
    'mdtraj_PDBTrajectoryFile': 'mdtraj',
    'file_xtc': 'mdtraj',
    'file_dcd': 'mdtraj',
    'file_h5': 'mdtraj',
    'file_mmtf': 'mdtraj',
    'openmm_Topology': 'openmm',
    'openmm_System': 'openmm',
    'openmm_Context': 'openmm',
    'openmm_Simulation': 'openmm',
    'openmm_Modeller': 'openmm',
    'openmm_PDBFile': 'openmm',
    'openmm_GromacsGroFile': 'openmm',
    'file_inpcrd': 'openmm',
    'file_prmtop': 'openmm',
    'file_psf': 'openmm',
    'file_gro': 'openmm',
    'MDAnalysis_Universe': 'MDAnalysis',
    'MDAnalysis_Topology': 'MDAnalysis',
    'MDAnalysis_AtomGroup': 'MDAnalysis',
    'MDAnalysis_topology_PDBParser': 'MDAnalysis',
    'nglview_NGLWidget': 'nglview',
    'molsysviewer_MolSysView': 'molsysviewer',
    'rdkit_Mol': 'rdkit',
    'string_smiles': 'rdkit',
    'file_smi': 'rdkit',
    'openff_Molecule': 'openff.toolkit',
    'openff_Topology': 'openff.toolkit',
    'parmed_Structure': 'parmed',
    'parmed_GromacsTopologyFile': 'parmed',
    'file_mol2': 'parmed',
    'file_top': 'parmed',
    'pytraj_Trajectory': 'pytraj',
    'pytraj_Topology': 'pytraj',
    'pdbfixer_PDBFixer': 'pdbfixer',
    'biopython_Seq': 'Bio',
    'biopython_SeqRecord': 'Bio',
    'biopython_PDBStructure': 'Bio',
    'mmtf_MMTFDecoder': 'mmtf',
    'file_molsys_yaml': 'yaml',
    'file_topology_yaml': 'yaml',
    'file_structures_yaml': 'yaml',
}

SHOW_ALL_CAPABILITIES = True
EXCEPTION_CLASS = LibraryNotFoundError
