"""
Unit and regression test for the get_sequence_alignment module of the molsysmt package on molsysmt MolSys molecular
systems.
"""

# Import package, test suite, and other packages as needed
import molsysmt as msm
from molsysmt import systems
import numpy as np

# Distance between atoms in space and time

def test_get_sequence_alignment_molsysmt_MolSys_1():
    molsys = msm.convert(systems['T4 lysozyme L99A']['181l.h5msm'], to_form='molsysmt.MolSys')
    molsys_2 = msm.convert(systems['T4 lysozyme L99A']['1l17.h5msm'], to_form='molsysmt.MolSys')
    seq, ref_seq = msm.topology.get_sequence_alignment(molsys, selection='molecule_type=="protein"',
                                    reference_molecular_system=molsys_2, reference_selection='molecule_type=="protein"',
                                    prettyprint=False)
    seq_true = 'MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAAAINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYK--'
    ref_seq_true = 'MNVFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNCNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRCALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL'
    assert (seq==seq_true) and (ref_seq==ref_seq_true)

def test_get_sequence_alignment_molsysmt_MolSys_2(capsys):
    msm.topology.get_sequence_alignment('AALVRDAVR', reference_molecular_system='EAALFNDAVRQ', prettyprint=True)
    captured = capsys.readouterr()
    assert captured.out=='-AAL\x1b[1;31;48mV\x1b[m\x1b[1;31;48mR\x1b[mDAVR-\n\n\x1b[1;34;48mE\x1b[mAAL\x1b[1;31;48mF\x1b[m\x1b[1;31;48mN\x1b[mDAVR\x1b[1;34;48mQ\x1b[m\n'

def test_get_sequence_alignment_molsysmt_MolSys_3(capsys):
    molsys_X = msm.convert('2NZT')
    molsys_X = msm.remove(molsys_X, selection='molecule_type!="protein"')
    molsys_X_A = msm.extract(molsys_X, selection='chain_name=="A"')
    molsys_AF = msm.convert('AF-P52789-F1')
    msm.topology.get_sequence_alignment(molsys_AF, reference_molecular_system=molsys_X_A, prettyprint=True)
    captured = capsys.readouterr()
    assert captured.out=='\x1b[1;34;48mM\x1b[m\x1b[1;34;48mI\x1b[m\x1b[1;34;48mA\x1b[m\x1b[1;34;48mS\x1b[m\x1b[1;34;48mH\x1b[m\x1b[1;34;48mL\x1b[m\x1b[1;34;48mL\x1b[m\x1b[1;34;48mA\x1b[m\x1b[1;34;48mY\x1b[m\x1b[1;34;48mF\x1b[m\x1b[1;34;48mF\x1b[m\x1b[1;34;48mT\x1b[m\x1b[1;34;48mE\x1b[m\x1b[1;34;48mL\x1b[m\x1b[1;34;48mN\x1b[m\x1b[1;34;48mH\x1b[mDQVQKVDQYLYHMRLSDETLLEISKRFRKEMEKGLGATTHPTAAVKMLPTFVRSTPDGTEHGEFLALDLGGTNFRVLWVKV\x1b[1;34;48mT\x1b[m\x1b[1;34;48mD\x1b[m\x1b[1;34;48mN\x1b[m\x1b[1;34;48mG\x1b[m\x1b[1;34;48mL\x1b[m\x1b[1;34;48mQ\x1b[m\x1b[1;34;48mK\x1b[mVEMENQIYAIPEDIMRGSGTQLFDHIAECLANFMDKLQIKDKKLPLGFTFSFPCHQTKLDESFLVSWTKGFKSSGVEGRDVVALIRKAIQRRGDFDIDIVAVVNDTVGTMMTCGYDDHNCEIGLIVGTGSNACYMEEMRHIDMVEGDEGRMCINMEWGAFGDDGSLNDIRTEFDQEIDMGSLNPGKQLFEKMISGMYMGELVRLILVKMAKEELLFGGKLSPELLNTGRFETKDISDIEGEKDGIRKAREVLMRLGLDPTQEDCVATHRICQIVSTRSASLCAATLAAVLQRIKENKGEERLRSTIGVDGSVYKKHPHFAKRLHKTVRRLVPGCDVRFLRSEDGSGKGAAMVTAVAYRLADQHRARQKTLEHLQLSHDQLLEVKRRMKVEMERGLSKETHASAPVKMLPTYVC\x1b[1;34;48mA\x1b[m\x1b[1;34;48mT\x1b[m\x1b[1;34;48mP\x1b[m\x1b[1;34;48mD\x1b[m\x1b[1;34;48mG\x1b[m\x1b[1;34;48mT\x1b[m\x1b[1;34;48mE\x1b[m\x1b[1;34;48mK\x1b[mGDFLALDLGGTNFRVLLVRVR\x1b[1;34;48mN\x1b[m\x1b[1;34;48mG\x1b[m\x1b[1;34;48mK\x1b[m\x1b[1;34;48mW\x1b[m\x1b[1;34;48mG\x1b[mGVEMHNKIYAIPQEVMHGTGDELFDHIVQCIADFLEYMGM\x1b[1;34;48mK\x1b[m\x1b[1;34;48mG\x1b[m\x1b[1;34;48mV\x1b[mSLPLGFTFSFPCQQNSLDESILLKWTKGFKASGCEGEDVVTLLKEAIHRR\x1b[1;34;48mE\x1b[m\x1b[1;34;48mE\x1b[m\x1b[1;34;48mF\x1b[mDLDVVAVVNDTVGTMMTCGFEDPHCEVGLIVGTGSNACYMEEMRNVELVEGEEGRMCVNMEWGAFGDNGCLDDFRTEFDVAVDELSLNPGKQRFEKMISGMYLGEIVRNILIDFTKRGLLFRGRISERLKTRGIFETKFLSQIESDCLALLQVRAILQHLGLESTCDDSIIVKEVCTVVARRAAQLCGAGMAAVVDRIRENRGLDALKVTVGVDGTLYKLHPHFAKVMHETVKDLAPKCDVSFLQSEDGSGKGAALITAVACRIRE\x1b[1;34;48mA\x1b[m\x1b[1;34;48mG\x1b[m\x1b[1;34;48mQ\x1b[m\x1b[1;34;48mR\x1b[m\n\n----------------DQVQKVDQYLYHMRLSDETLLEISKRFRKEMEKGLGATTHPTAAVKMLPTFVRSTPDGTEHGEFLALDLGGTNFRVLWVKV-------VEMENQIYAIPEDIMRGSGTQLFDHIAECLANFMDKLQIKDKKLPLGFTFSFPCHQTKLDESFLVSWTKGFKSSGVEGRDVVALIRKAIQRRGDFDIDIVAVVNDTVGTMMTCGYDDHNCEIGLIVGTGSNACYMEEMRHIDMVEGDEGRMCINMEWGAFGDDGSLNDIRTEFDQEIDMGSLNPGKQLFEKMISGMYMGELVRLILVKMAKEELLFGGKLSPELLNTGRFETKDISDIEGEKDGIRKAREVLMRLGLDPTQEDCVATHRICQIVSTRSASLCAATLAAVLQRIKENKGEERLRSTIGVDGSVYKKHPHFAKRLHKTVRRLVPGCDVRFLRSEDGSGKGAAMVTAVAYRLADQHRARQKTLEHLQLSHDQLLEVKRRMKVEMERGLSKETHASAPVKMLPTYVC--------GDFLALDLGGTNFRVLLVRVR-----GVEMHNKIYAIPQEVMHGTGDELFDHIVQCIADFLEYMGM---SLPLGFTFSFPCQQNSLDESILLKWTKGFKASGCEGEDVVTLLKEAIHRR---DLDVVAVVNDTVGTMMTCGFEDPHCEVGLIVGTGSNACYMEEMRNVELVEGEEGRMCVNMEWGAFGDNGCLDDFRTEFDVAVDELSLNPGKQRFEKMISGMYLGEIVRNILIDFTKRGLLFRGRISERLKTRGIFETKFLSQIESDCLALLQVRAILQHLGLESTCDDSIIVKEVCTVVARRAAQLCGAGMAAVVDRIRENRGLDALKVTVGVDGTLYKLHPHFAKVMHETVKDLAPKCDVSFLQSEDGSGKGAALITAVACRIRE----\n'

