
def _raise_not_implemented_error(item, indices=None, frame_indices=None):
    raise NotImplementedError

target_fields = {

        'atom' : {
            'name' : _raise_not_implemented_error,
            'index' : _raise_not_implemented_error,
            'id' : _raise_not_implemented_error,
            'type' : _raise_not_implemented_error,
            'element' : _raise_not_implemented_error,
            'n_atoms' : _raise_not_implemented_error,
            'atom_name' : _raise_not_implemented_error,
            'atom_index' : _raise_not_implemented_error,
            'atom_id' : _raise_not_implemented_error,
            'atom_type' : _raise_not_implemented_error,
            'n_groups' : _raise_not_implemented_error,
            'group_name' : _raise_not_implemented_error,
            'group_index' : _raise_not_implemented_error,
            'group_id' : _raise_not_implemented_error,
            'chain_index' : _raise_not_implemented_error,
            'chain_id' : _raise_not_implemented_error,
            'chain_name' : _raise_not_implemented_error,
            'n_frames' : _raise_not_implemented_error,
            'n_chains' : _raise_not_implemented_error,
            'n_molecules' : _raise_not_implemented_error,
            'n_aminoacids' : _raise_not_implemented_error,
            'n_nucleotides' : _raise_not_implemented_error,
            'n_waters' : _raise_not_implemented_error,
            'n_ions' : _raise_not_implemented_error,
            'n_bonds' : _raise_not_implemented_error,
            'masses' : _raise_not_implemented_error,
            'charge' : _raise_not_implemented_error,
            'net_charge' : _raise_not_implemented_error,
            'bonded_atoms' : _raise_not_implemented_error,
            'bonds' : _raise_not_implemented_error,
            'graph' : _raise_not_implemented_error,
            'molecules' : _raise_not_implemented_error,
            'molecule_type' : _raise_not_implemented_error,
            'coordinates' : _raise_not_implemented_error,
            'frames': _raise_not_implemented_error
            },

        'group' : {
            'name' : _raise_not_implemented_error,
            'index' : _raise_not_implemented_error,
            'id' : _raise_not_implemented_error,
            'type' : _raise_not_implemented_error,
            'atom_name' : _raise_not_implemented_error,
            'atom_index' : _raise_not_implemented_error,
            'atom_id' : _raise_not_implemented_error,
            'atom_type' : _raise_not_implemented_error,
            'n_groups' : _raise_not_implemented_error,
            'group_name' : _raise_not_implemented_error,
            'group_index' : _raise_not_implemented_error,
            'group_id' : _raise_not_implemented_error,
            'chain_index' : _raise_not_implemented_error,
            'chain_id' : _raise_not_implemented_error,
            'n_frames' : _raise_not_implemented_error,
            'n_chains' : _raise_not_implemented_error,
            'n_molecules' : _raise_not_implemented_error,
            'n_aminoacids' : _raise_not_implemented_error,
            'n_nucleotides' : _raise_not_implemented_error,
            'n_waters' : _raise_not_implemented_error,
            'n_ions' : _raise_not_implemented_error,
            'n_bonds' : _raise_not_implemented_error,
            'masses' : _raise_not_implemented_error,
            'charge' : _raise_not_implemented_error,
            'net_charge' : _raise_not_implemented_error,
            'bonded_atoms' : _raise_not_implemented_error,
            'bonds' : _raise_not_implemented_error,
            'graph' : _raise_not_implemented_error,
            'molecules' : _raise_not_implemented_error,
            'molecule_type' : _raise_not_implemented_error,
            'coordinates' : _raise_not_implemented_error,
            'frames': _raise_not_implemented_error
            },

        'chain' : {
            'name' : _raise_not_implemented_error,
            'index' : _raise_not_implemented_error,
            'id' : _raise_not_implemented_error,
            'type' : _raise_not_implemented_error,
            'atom_name' : _raise_not_implemented_error,
            'atom_index' : _raise_not_implemented_error,
            'atom_id' : _raise_not_implemented_error,
            'atom_type' : _raise_not_implemented_error,
            'n_groups' : _raise_not_implemented_error,
            'group_name' : _raise_not_implemented_error,
            'group_index' : _raise_not_implemented_error,
            'group_id' : _raise_not_implemented_error,
            'chain_index' : _raise_not_implemented_error,
            'chain_id' : _raise_not_implemented_error,
            'n_frames' : _raise_not_implemented_error,
            'n_chains' : _raise_not_implemented_error,
            'n_molecules' : _raise_not_implemented_error,
            'n_aminoacids' : _raise_not_implemented_error,
            'n_nucleotides' : _raise_not_implemented_error,
            'n_waters' : _raise_not_implemented_error,
            'n_ions' : _raise_not_implemented_error,
            'n_bonds' : _raise_not_implemented_error,
            'masses' : _raise_not_implemented_error,
            'charge' : _raise_not_implemented_error,
            'net_charge' : _raise_not_implemented_error,
            'bonded_atoms' : _raise_not_implemented_error,
            'bonds' : _raise_not_implemented_error,
            'graph' : _raise_not_implemented_error,
            'molecules' : _raise_not_implemented_error,
            'molecule_type' : _raise_not_implemented_error,
            'coordinates' : _raise_not_implemented_error,
            'frames': _raise_not_implemented_error
            },

        'molecule' : {
            'name' : _raise_not_implemented_error,
            'index' : _raise_not_implemented_error,
            'id' : _raise_not_implemented_error,
            'type' : _raise_not_implemented_error,
            'atom_name' : _raise_not_implemented_error,
            'atom_index' : _raise_not_implemented_error,
            'atom_id' : _raise_not_implemented_error,
            'atom_type' : _raise_not_implemented_error,
            'n_groups' : _raise_not_implemented_error,
            'group_name' : _raise_not_implemented_error,
            'group_index' : _raise_not_implemented_error,
            'group_id' : _raise_not_implemented_error,
            'chain_index' : _raise_not_implemented_error,
            'chain_id' : _raise_not_implemented_error,
            'n_frames' : _raise_not_implemented_error,
            'n_chains' : _raise_not_implemented_error,
            'n_molecules' : _raise_not_implemented_error,
            'n_aminoacids' : _raise_not_implemented_error,
            'n_nucleotides' : _raise_not_implemented_error,
            'n_waters' : _raise_not_implemented_error,
            'n_ions' : _raise_not_implemented_error,
            'n_bonds' : _raise_not_implemented_error,
            'masses' : _raise_not_implemented_error,
            'charge' : _raise_not_implemented_error,
            'net_charge' : _raise_not_implemented_error,
            'bonded_atoms' : _raise_not_implemented_error,
            'bonds' : _raise_not_implemented_error,
            'graph' : _raise_not_implemented_error,
            'coordinates' : _raise_not_implemented_error,
            'frames': _raise_not_implemented_error
            },

        'system' : {
            'form' : _raise_not_implemented_error,
            'name' : _raise_not_implemented_error,
            'index' : _raise_not_implemented_error,
            'id' : _raise_not_implemented_error,
            'type' : _raise_not_implemented_error,
            'n_atoms' : _raise_not_implemented_error,
            'atom_name' : _raise_not_implemented_error,
            'atom_index' : _raise_not_implemented_error,
            'atom_id' : _raise_not_implemented_error,
            'atom_type' : _raise_not_implemented_error,
            'n_groups' : _raise_not_implemented_error,
            'group_name' : _raise_not_implemented_error,
            'group_index' : _raise_not_implemented_error,
            'group_id' : _raise_not_implemented_error,
            'chain_index' : _raise_not_implemented_error,
            'chain_id' : _raise_not_implemented_error,
            'n_frames' : _raise_not_implemented_error,
            'n_chains' : _raise_not_implemented_error,
            'n_molecules' : _raise_not_implemented_error,
            'n_aminoacids' : _raise_not_implemented_error,
            'n_nucleotides' : _raise_not_implemented_error,
            'n_waters' : _raise_not_implemented_error,
            'n_ions' : _raise_not_implemented_error,
            'n_bonds' : _raise_not_implemented_error,
            'masses' : _raise_not_implemented_error,
            'charge' : _raise_not_implemented_error,
            'net_charge' : _raise_not_implemented_error,
            'bonded_atoms' : _raise_not_implemented_error,
            'bonds' : _raise_not_implemented_error,
            'graph' : _raise_not_implemented_error,
            'molecules' : _raise_not_implemented_error,
            'coordinates' : _raise_not_implemented_error,
            'box' : _raise_not_implemented_error,
            'box_lengths' : _raise_not_implemented_error,
            'box_angles' : _raise_not_implemented_error,
            'box_shape' : _raise_not_implemented_error,
            'time' : _raise_not_implemented_error,
            'step' : _raise_not_implemented_error,
            'frames': _raise_not_implemented_error,
            'length_units': _raise_not_implemented_error,
            'time_units': _raise_not_implemented_error
            }
        }

