"""
Tests for file_bcif_gz/get_topological_attributes.py.

Oracle: 1vii.bcif.gz — chicken villin HP35, 36 residues (amino acids), 596 atoms,
1 chain, 1 molecule, 1 component, 1 entity, 602 bonds.

All 342 getter functions are exercised in one of three parametrized test groups:
  - scalar:      function returns a single integer value
  - flat_list:   function returns a flat list with a known length
  - nested_list: function returns a list of lists with a known outer length
"""

import pytest
from molsysmt.form.file_bcif_gz import get_topological_attributes as aux


@pytest.fixture()
def hp35(hp35_bcif_gz_file):
    return str(hp35_bcif_gz_file)


# ---------------------------------------------------------------------------
# Scalar-returning getters — exact expected values
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("func_name,expected", [
    ("get_n_amino_acids_from_atom",        36),
    ("get_n_amino_acids_from_group",       36),
    ("get_n_amino_acids_from_system",      36),
    ("get_n_atoms_from_atom",              596),
    ("get_n_atoms_from_system",            596),
    ("get_n_bonds_from_bond",              602),
    ("get_n_bonds_from_system",            602),
    ("get_n_chains_from_atom",             1),
    ("get_n_chains_from_chain",            1),
    ("get_n_chains_from_system",           1),
    ("get_n_components_from_atom",         1),
    ("get_n_components_from_component",    1),
    ("get_n_components_from_system",       1),
    ("get_n_dnas_from_atom",               0),
    ("get_n_dnas_from_component",          0),
    ("get_n_dnas_from_group",              0),
    ("get_n_dnas_from_molecule",           0),
    ("get_n_dnas_from_system",             0),
    ("get_n_entities_from_atom",           1),
    ("get_n_entities_from_component",      1),
    ("get_n_entities_from_entity",         1),
    ("get_n_entities_from_group",          1),
    ("get_n_entities_from_molecule",       1),
    ("get_n_entities_from_system",         1),
    ("get_n_groups_from_atom",             36),
    ("get_n_groups_from_group",            36),
    ("get_n_groups_from_system",           36),
    ("get_n_ions_from_atom",               0),
    ("get_n_ions_from_group",              0),
    ("get_n_ions_from_system",             0),
    ("get_n_lipids_from_atom",             0),
    ("get_n_lipids_from_group",            0),
    ("get_n_lipids_from_system",           0),
    ("get_n_molecules_from_atom",          1),
    ("get_n_molecules_from_component",     1),
    ("get_n_molecules_from_group",         1),
    ("get_n_molecules_from_molecule",      1),
    ("get_n_molecules_from_system",        1),
    ("get_n_nucleotides_from_atom",        0),
    ("get_n_nucleotides_from_group",       0),
    ("get_n_nucleotides_from_system",      0),
    ("get_n_peptides_from_atom",           1),
    ("get_n_peptides_from_component",      1),
    ("get_n_peptides_from_group",          1),
    ("get_n_peptides_from_molecule",       1),
    ("get_n_peptides_from_system",         1),
    ("get_n_polysaccharides_from_atom",    0),
    ("get_n_polysaccharides_from_component", 0),
    ("get_n_polysaccharides_from_group",   0),
    ("get_n_polysaccharides_from_molecule", 0),
    ("get_n_polysaccharides_from_system",  0),
    ("get_n_proteins_from_atom",           0),
    ("get_n_proteins_from_component",      0),
    ("get_n_proteins_from_group",          0),
    ("get_n_proteins_from_molecule",       0),
    ("get_n_proteins_from_system",         0),
    ("get_n_rnas_from_atom",               0),
    ("get_n_rnas_from_component",          0),
    ("get_n_rnas_from_group",              0),
    ("get_n_rnas_from_molecule",           0),
    ("get_n_rnas_from_system",             0),
    ("get_n_saccharides_from_atom",        0),
    ("get_n_saccharides_from_group",       0),
    ("get_n_saccharides_from_system",      0),
    ("get_n_small_molecules_from_atom",    0),
    ("get_n_small_molecules_from_group",   0),
    ("get_n_small_molecules_from_system",  0),
    ("get_n_waters_from_atom",             0),
    ("get_n_waters_from_group",            0),
    ("get_n_waters_from_system",           0),
])
def test_scalar(hp35, func_name, expected):
    result = getattr(aux, func_name)(hp35)
    assert result == expected


# ---------------------------------------------------------------------------
# Flat-list-returning getters — check list length
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("func_name,expected_len", [
    ("get_atom_id_from_atom",              596),
    ("get_atom_index_from_atom",           596),
    ("get_atom_name_from_atom",            596),
    ("get_atom_type_from_atom",            596),
    ("get_bond_index_from_bond",           602),
    ("get_bond_index_from_system",         602),
    ("get_bond_order_from_bond",           602),
    ("get_bond_type_from_bond",            602),
    ("get_bonded_atoms_from_bond",         596),
    ("get_bonded_atoms_from_system",       596),
    ("get_chain_id_from_atom",             596),
    ("get_chain_id_from_chain",            1),
    ("get_chain_id_from_component",        1),
    ("get_chain_id_from_group",            36),
    ("get_chain_id_from_molecule",         1),
    ("get_chain_index_from_atom",          596),
    ("get_chain_index_from_chain",         1),
    ("get_chain_index_from_component",     1),
    ("get_chain_index_from_group",         36),
    ("get_chain_index_from_molecule",      1),
    ("get_chain_name_from_atom",           596),
    ("get_chain_name_from_chain",          1),
    ("get_chain_name_from_component",      1),
    ("get_chain_name_from_group",          36),
    ("get_chain_name_from_molecule",       1),
    ("get_chain_type_from_atom",           596),
    ("get_chain_type_from_chain",          1),
    ("get_chain_type_from_component",      1),
    ("get_chain_type_from_group",          36),
    ("get_chain_type_from_molecule",       1),
    ("get_component_id_from_atom",         596),
    ("get_component_id_from_component",    1),
    ("get_component_id_from_group",        36),
    ("get_component_index_from_atom",      596),
    ("get_component_index_from_component", 1),
    ("get_component_index_from_group",     36),
    ("get_component_name_from_atom",       596),
    ("get_component_name_from_component",  1),
    ("get_component_name_from_group",      36),
    ("get_component_type_from_atom",       596),
    ("get_component_type_from_component",  1),
    ("get_component_type_from_group",      36),
    ("get_entity_id_from_atom",            596),
    ("get_entity_id_from_component",       1),
    ("get_entity_id_from_entity",          1),
    ("get_entity_id_from_group",           36),
    ("get_entity_id_from_molecule",        1),
    ("get_entity_index_from_atom",         596),
    ("get_entity_index_from_component",    1),
    ("get_entity_index_from_group",        36),
    ("get_entity_index_from_molecule",     1),
    ("get_entity_name_from_atom",          596),
    ("get_entity_name_from_component",     1),
    ("get_entity_name_from_entity",        1),
    ("get_entity_name_from_group",         36),
    ("get_entity_name_from_molecule",      1),
    ("get_entity_type_from_atom",          596),
    ("get_entity_type_from_component",     1),
    ("get_entity_type_from_entity",        1),
    ("get_entity_type_from_group",         36),
    ("get_entity_type_from_molecule",      1),
    ("get_group_id_from_atom",             596),
    ("get_group_id_from_group",            36),
    ("get_group_index_from_atom",          596),
    ("get_group_index_from_group",         36),
    ("get_group_name_from_atom",           596),
    ("get_group_name_from_group",          36),
    ("get_group_type_from_atom",           596),
    ("get_group_type_from_group",          36),
    ("get_inner_bond_index_from_system",   602),
    ("get_inner_bonded_atoms_from_system", 596),
    ("get_molecule_id_from_atom",          596),
    ("get_molecule_id_from_component",     1),
    ("get_molecule_id_from_group",         36),
    ("get_molecule_id_from_molecule",      1),
    ("get_molecule_index_from_atom",       596),
    ("get_molecule_index_from_component",  1),
    ("get_molecule_index_from_group",      36),
    ("get_molecule_index_from_molecule",   1),
    ("get_molecule_name_from_atom",        596),
    ("get_molecule_name_from_component",   1),
    ("get_molecule_name_from_group",       36),
    ("get_molecule_name_from_molecule",    1),
    ("get_molecule_type_from_atom",        596),
    ("get_molecule_type_from_component",   1),
    ("get_molecule_type_from_group",       36),
    ("get_molecule_type_from_molecule",    1),
    ("get_n_amino_acids_from_chain",       1),
    ("get_n_amino_acids_from_component",   1),
    ("get_n_amino_acids_from_entity",      1),
    ("get_n_amino_acids_from_molecule",    1),
    ("get_n_atoms_from_chain",             1),
    ("get_n_atoms_from_component",         1),
    ("get_n_atoms_from_entity",            1),
    ("get_n_atoms_from_group",             36),
    ("get_n_atoms_from_molecule",          1),
    ("get_n_bonds_from_atom",              596),
    ("get_n_bonds_from_chain",             1),
    ("get_n_bonds_from_component",         1),
    ("get_n_bonds_from_entity",            1),
    ("get_n_bonds_from_group",             36),
    ("get_n_bonds_from_molecule",          1),
    ("get_n_chains_from_component",        1),
    ("get_n_chains_from_entity",           1),
    ("get_n_chains_from_group",            36),
    ("get_n_chains_from_molecule",         1),
    ("get_n_components_from_chain",        1),
    ("get_n_components_from_entity",       1),
    ("get_n_components_from_group",        36),
    ("get_n_components_from_molecule",     1),
    ("get_n_dnas_from_chain",              1),
    ("get_n_dnas_from_entity",             1),
    ("get_n_entities_from_chain",          1),
    ("get_n_groups_from_chain",            1),
    ("get_n_groups_from_component",        1),
    ("get_n_groups_from_entity",           1),
    ("get_n_groups_from_molecule",         1),
    ("get_n_inner_bonds_from_atom",        596),
    ("get_n_inner_bonds_from_chain",       1),
    ("get_n_inner_bonds_from_component",   1),
    ("get_n_inner_bonds_from_entity",      1),
    ("get_n_inner_bonds_from_group",       36),
    ("get_n_inner_bonds_from_molecule",    1),
    ("get_n_ions_from_chain",              1),
    ("get_n_ions_from_component",          1),
    ("get_n_ions_from_entity",             1),
    ("get_n_ions_from_molecule",           1),
    ("get_n_lipids_from_chain",            1),
    ("get_n_lipids_from_component",        1),
    ("get_n_lipids_from_entity",           1),
    ("get_n_lipids_from_molecule",         1),
    ("get_n_molecules_from_chain",         1),
    ("get_n_molecules_from_entity",        1),
    ("get_n_nucleotides_from_chain",       1),
    ("get_n_nucleotides_from_component",   1),
    ("get_n_nucleotides_from_entity",      1),
    ("get_n_nucleotides_from_molecule",    1),
    ("get_n_peptides_from_chain",          1),
    ("get_n_peptides_from_entity",         1),
    ("get_n_polysaccharides_from_chain",   1),
    ("get_n_polysaccharides_from_entity",  1),
    ("get_n_proteins_from_chain",          1),
    ("get_n_proteins_from_entity",         1),
    ("get_n_rnas_from_chain",              1),
    ("get_n_rnas_from_entity",             1),
    ("get_n_saccharides_from_chain",       1),
    ("get_n_saccharides_from_component",   1),
    ("get_n_saccharides_from_entity",      1),
    ("get_n_saccharides_from_molecule",    1),
    ("get_n_small_molecules_from_chain",   1),
    ("get_n_small_molecules_from_component", 1),
    ("get_n_small_molecules_from_entity",  1),
    ("get_n_small_molecules_from_molecule", 1),
    ("get_n_waters_from_chain",            1),
    ("get_n_waters_from_component",        1),
    ("get_n_waters_from_entity",           1),
    ("get_n_waters_from_molecule",         1),
])
def test_flat_list(hp35, func_name, expected_len):
    result = getattr(aux, func_name)(hp35)
    assert isinstance(result, list)
    assert len(result) == expected_len


# ---------------------------------------------------------------------------
# Nested-list-returning getters — check outer list length
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("func_name,expected_outer_len", [
    ("get_atom_id_from_chain",                  1),
    ("get_atom_id_from_component",              1),
    ("get_atom_id_from_entity",                 1),
    ("get_atom_id_from_group",                  36),
    ("get_atom_id_from_molecule",               1),
    ("get_atom_index_from_chain",               1),
    ("get_atom_index_from_component",           1),
    ("get_atom_index_from_entity",              1),
    ("get_atom_index_from_group",               36),
    ("get_atom_index_from_molecule",            1),
    ("get_atom_name_from_chain",                1),
    ("get_atom_name_from_component",            1),
    ("get_atom_name_from_entity",               1),
    ("get_atom_name_from_group",                36),
    ("get_atom_name_from_molecule",             1),
    ("get_atom_type_from_chain",                1),
    ("get_atom_type_from_component",            1),
    ("get_atom_type_from_entity",               1),
    ("get_atom_type_from_group",                36),
    ("get_atom_type_from_molecule",             1),
    ("get_bond_index_from_atom",                596),
    ("get_bond_index_from_chain",               1),
    ("get_bond_index_from_component",           1),
    ("get_bond_index_from_entity",              1),
    ("get_bond_index_from_group",               36),
    ("get_bond_index_from_molecule",            1),
    ("get_bond_order_from_atom",                596),
    ("get_bond_order_from_chain",               1),
    ("get_bond_order_from_component",           1),
    ("get_bond_order_from_entity",              1),
    ("get_bond_order_from_group",               36),
    ("get_bond_order_from_molecule",            1),
    ("get_bond_type_from_atom",                 596),
    ("get_bond_type_from_chain",                1),
    ("get_bond_type_from_component",            1),
    ("get_bond_type_from_entity",               1),
    ("get_bond_type_from_group",                36),
    ("get_bond_type_from_molecule",             1),
    ("get_bonded_atom_pairs_from_atom",         602),
    ("get_bonded_atom_pairs_from_chain",        1),
    ("get_bonded_atom_pairs_from_component",    1),
    ("get_bonded_atom_pairs_from_entity",       1),
    ("get_bonded_atom_pairs_from_group",        36),
    ("get_bonded_atom_pairs_from_molecule",     1),
    ("get_bonded_atom_pairs_from_system",       602),
    ("get_bonded_atoms_from_atom",              596),
    ("get_bonded_atoms_from_chain",             1),
    ("get_bonded_atoms_from_component",         1),
    ("get_bonded_atoms_from_entity",            1),
    ("get_bonded_atoms_from_group",             36),
    ("get_bonded_atoms_from_molecule",          1),
    ("get_chain_id_from_entity",                1),
    ("get_chain_index_from_entity",             1),
    ("get_chain_name_from_entity",              1),
    ("get_chain_type_from_entity",              1),
    ("get_component_id_from_chain",             1),
    ("get_component_id_from_entity",            1),
    ("get_component_id_from_molecule",          1),
    ("get_component_index_from_chain",          1),
    ("get_component_index_from_entity",         1),
    ("get_component_index_from_molecule",       1),
    ("get_component_name_from_chain",           1),
    ("get_component_name_from_entity",          1),
    ("get_component_name_from_molecule",        1),
    ("get_component_type_from_chain",           1),
    ("get_component_type_from_entity",          1),
    ("get_component_type_from_molecule",        1),
    ("get_entity_id_from_chain",                1),
    ("get_entity_index_from_chain",             1),
    ("get_entity_index_from_entity",            1),
    ("get_entity_name_from_chain",              1),
    ("get_entity_type_from_chain",              1),
    ("get_group_id_from_chain",                 1),
    ("get_group_id_from_component",             1),
    ("get_group_id_from_entity",                1),
    ("get_group_id_from_molecule",              1),
    ("get_group_index_from_chain",              1),
    ("get_group_index_from_component",          1),
    ("get_group_index_from_entity",             1),
    ("get_group_index_from_molecule",           1),
    ("get_group_name_from_chain",               1),
    ("get_group_name_from_component",           1),
    ("get_group_name_from_entity",              1),
    ("get_group_name_from_molecule",            1),
    ("get_group_type_from_chain",               1),
    ("get_group_type_from_component",           1),
    ("get_group_type_from_entity",              1),
    ("get_group_type_from_molecule",            1),
    ("get_inner_bond_index_from_atom",          596),
    ("get_inner_bond_index_from_chain",         1),
    ("get_inner_bond_index_from_component",     1),
    ("get_inner_bond_index_from_entity",        1),
    ("get_inner_bond_index_from_group",         36),
    ("get_inner_bond_index_from_molecule",      1),
    ("get_inner_bonded_atom_pairs_from_atom",   602),
    ("get_inner_bonded_atom_pairs_from_chain",  1),
    ("get_inner_bonded_atom_pairs_from_component", 1),
    ("get_inner_bonded_atom_pairs_from_entity", 1),
    ("get_inner_bonded_atom_pairs_from_group",  36),
    ("get_inner_bonded_atom_pairs_from_molecule", 1),
    ("get_inner_bonded_atom_pairs_from_system", 602),
    ("get_inner_bonded_atoms_from_atom",        596),
    ("get_inner_bonded_atoms_from_chain",       1),
    ("get_inner_bonded_atoms_from_component",   1),
    ("get_inner_bonded_atoms_from_entity",      1),
    ("get_inner_bonded_atoms_from_group",       36),
    ("get_inner_bonded_atoms_from_molecule",    1),
    ("get_molecule_id_from_chain",              1),
    ("get_molecule_id_from_entity",             1),
    ("get_molecule_index_from_chain",           1),
    ("get_molecule_index_from_entity",          1),
    ("get_molecule_name_from_chain",            1),
    ("get_molecule_name_from_entity",           1),
    ("get_molecule_type_from_chain",            1),
    ("get_molecule_type_from_entity",           1),
])
def test_nested_list(hp35, func_name, expected_outer_len):
    result = getattr(aux, func_name)(hp35)
    assert isinstance(result, list)
    assert len(result) == expected_outer_len
