name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package to platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] #[macOS-latest, ubuntu-latest]
        python-version: [3.7]

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a

    - name: Symlink gfortran (macOS)
      if: runner.os == 'macOS'
      run: |
        sudo ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
        sudo mkdir /usr/local/gfortran
        sudo ln -s /usr/local/Cellar/gcc@10/*/lib/gcc/10 /usr/local/gfortran/lib

    - name: Checking gfortran version
      run: |
        gfortran --version

    - name: Conda environment creation and activation
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true

    - name: Build and upload the conda packages
      uses: uibcdf/action-build-and-upload-conda-packages@v1.1.0
      with:
        meta_yaml_dir: devtools/conda-build
        python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
        user: uibcdf
        label: auto
        token: ${{ secrets.ANACONDA_UIBCDF_TOKEN }} # Replace with the right name of your secret

